### ISSUE TITLE
S View cover does not work

### ISSUE THREAD

**Issue by ruben2020** [JDCTeam/issue_tracking_cm#1]
S View cover does not work in version 20150616.

**Comment by B--B** [comment]
Please provide a log or report is unuseful..
However lid state works in that build and phone is correctly put in sleep state, this is the log:

I/PowerManagerService(  701): Going to sleep due to lid switch (uid 1000)...
I/PowerManagerService(  701): Sleeping (uid 1000)...

**Comment by ruben2020** [comment]
Yes, you are right. Closing the lid correctly puts the phone in sleep state.

But the S View feature works in the way that when the lid is closed, it should display the S View clock for several seconds before going to sleep. And if there is an incoming call AND the lid is closed, the S View phone display should show. https://youtu.be/fVMK2JC7z5Y

I'm not sure if the CyanogenMod base software has this feature, but the GPE ROM definitely has it. Basically, I could be reporting a bug for a feature that doesn't exist.

I also tried Durka's [Hall Monitor](https://github.com/durka/hallmonitor) app, as suggested in some websites, but it doesn't work, probably because it was never tested in Android 5.1.1.

If the S View feature doesn't exist in this ROM, I would definitely request it. At least it should be configurable.

**Comment by ruben2020** [comment]
Some ROMs seem to have this feature as "Smart Cover" under Display and Light Settings.

**Comment by smeroni68** [comment]
Other than GPE (from Samsung, and no source code has been released) can you put here a link to a rom (NOT Samsung) that has this feature?

We know that CM11 has received some commits to enable it (enable means only the clock view, not the call answering), but it was no more ported/supported on the following 12 and 12.1...

Thanks for your help.

**Comment by ruben2020** [comment]
I have not tried this ROM myself, but it claims to have "smart cover":
http://forum.xda-developers.com/galaxy-s4/i9505-develop/rom-blisspop-v3-5-t3143661

**Comment by smeroni68** [comment]
We can confirm that on the rom you linked, there is no "smart cover" support as you are asking for... the commits they have are only to manage the enable/disable of lid open/close... As we already stated, there are no sources regarding the support of cover as on TW roms.

On Lollipop has been also removed some commands on power manager, so is not that easy to have this feature... I hope it is clear... we can try to do something, but honestly we do not know what is possible to do.

Regards.

JDC Team

**Comment by smeroni68** [comment]
Last thing: this is a request of a new feature, not an Issue...

**Comment by MatthewBooth** [comment]
S-View doesn't even work right on GPE, either, if we're being honest. If you want S-View, you need TouchWiz.

**Comment by smeroni68** [comment]
Thanks Matt... who knows better than you GPE!!!
