### ISSUE TITLE
Stweaks not working RE-OPENING

### ISSUE THREAD

**Issue by TessellatedGuy** [JDCTeam/issue_tracking_cm#10]
OMG you guys think im that dumb to not have root permissions enabled? It could be your mod's fault too right? Anyways some dudes at xda helped me out, so it turns out it WAS the rom's fault, had to flash supersu cos the developer options dont work for stweaks for some reason. You guys need to fix this so that root permissions actually work from dev options. Seriously, stop closing reports without the author's permission, it's considered "RUDE". This one, can be closed.

**Comment by smeroni68** [comment]
If the Privacy guard pop-up has been closed without answer (for example), the root is denied to the app... sorry, but we use integrated Privacy Guard without any problem.
In case this is a common issue, don't you think there must be other frequent post on xda that report this?

Instead of installing SuperSU, have you checked the status of root permissions related to Stweaks app through Privacy Guard?

**Comment by TessellatedGuy** [comment]
Hmm, if you say that if the pop up got closed without answer then maybe it could be the reason, well how do I check root permissions for stweaks through privacy guard?  (Wierd question)

**Comment by MatthewBooth** [comment]
Can I just point out that this is our Github page and we can and will close anything we wish with our without a reason given and that isn't rude,  but our right? 

I've never had an issue running STweaks with CM.

**Comment by smeroni68** [comment]
Menu -> Privacy -> Privacy Guard -> (three dots upper right) -> Advanced -> Root Access folder -> Stweak...

Here what you must see:

https://dl.dropboxusercontent.com/u/82930263/Doc%20Thread/Screenshot_2015-07-09-23-27-21.png

And please... do not give RUDE as definition of a closing of an "issue"... you are a guest, and we try to help...

**Comment by TessellatedGuy** [comment]
You are right MatthewBooth, BUT thinking that the problem is solved isn't a good idea. It's okay though, as it IS your page. I feel that you need to be more patient? To the reports..... Because it's rude to me. No offense.

**Comment by smeroni68** [comment]
FYI: I closed the issue posting the result that you posted on xda... if you check the time of the closing you will see...

**Comment by TessellatedGuy** [comment]
Thanks smeroni, but thought you would reply so but the case is even more peculiar...... It's not blocked from root permissions.....

**Comment by TessellatedGuy** [comment]
But I believe you guys might want to take a look at it. Maybe it's conflicting with some kind of app so thats why its just me?

**Comment by smeroni68** [comment]
But due to the fact you installed SuperSU, the root access has been modified... so we do not know the previous status of root...

**Comment by TessellatedGuy** [comment]
Does that reset privacy guard permissions if an individual root app is installed?

**Comment by smeroni68** [comment]
If you wanna try, open SuperSU, deny root to Stweaks, check that it fail with the error of no support...

Than open privacy guard and check the root status... I expect Deny...

Root access for app is a common in the OS... so if an app say Deny all report Deny...

**Comment by TessellatedGuy** [comment]
Hmm it's actually allowed completely even after I denied from SuperSU

**Comment by TessellatedGuy** [comment]
And after opening the app it still says no root support

**Comment by smeroni68** [comment]
So probably the Privacy Guard has been de-activated from SuperSU installation... but I think we talked of this "issue" enought... don't you think?

If you wanna be sure and belive us, do a full nandroid and do a clean install just for testing... after this check, you can restore the backup and continue using previous installation.

Regards

**Comment by smeroni68** [comment]
I close the Issue Report hoping you will not get this as a RUDE action...

**Comment by TessellatedGuy** [comment]
Ok thnx, I think i'll close this issue then. I'll try clean installing too.

**Comment by smeroni68** [comment]
OK... let us know on xda... Thanks!!

**Comment by MatthewBooth** [comment]
Glad you guys got this sorted :-)
