### ISSUE TITLE
adb logcat does not work

### ISSUE THREAD

**Issue by trulyliu** [JDCTeam/issue_tracking_cm#108]
Jfltezm

OptimizedCM-12.1-20160118-jflte.zip

BETA-SuperSU-v2.52.zip

open_gapps-arm-5.1-nano-20170513.zip

adb does not work.

adb logcat
Unable to open log device 'main'

**Comment by smeroni68** [comment]
Rom support is gone years ago! Sorry.

**Comment by trulyliu** [comment]
What is the latest release version?

**Comment by B--B** [comment]
https://github.com/AOSP-JF/proprietary_vendor_samsung/commit/b00659a395732f85c911101f50619ab22c6bb8ca

https://github.com/AOSP-JF/platform_device_samsung_jflte/commit/761585eda6c01a02c1d2619c012a16eb7419ec17

Try to compile the rom with these commits, logcat should work (at least it was working fine on our AOSP lp)
