### ISSUE TITLE
Stweaks not working (Again)

### ISSUE THREAD

**Issue by TessellatedGuy** [JDCTeam/issue_tracking_cm#11]
I guess installing SuperSU was a temporary fix, now the issue is even worse stweaks is just blank with just the icons on the top right. I have SuperSU granted root too. But it doesn't say "no root or kernel support". It's just aa blank screen with 3 icons on top. Please help :( I have done a clean install of this ROM as you said as well @smeroni68

**Comment by TessellatedGuy** [comment]
And if you want logs....I can't do that because I disabled Android logger from Stweaks way before to save battery and I guess the tweaks are still there. I checked using some log collecting apps and its all empty. Thats why I know Stweaks settings are sticking.

**Comment by AntaresOne** [comment]
@TessellatedGuy 
Try to force close the app and reopen, this must fix your issue. Remember that you need to wait half a minute after you see the Android homescreen before opening STweaks, otherwise you'll encounter errors like that.

Please do not report more than once for the same issue, just reopen after it's closed.

**Comment by TessellatedGuy** [comment]
Oh ok very sorry, I'm new to github so I didn't know I could reopen reports.....

**Comment by TessellatedGuy** [comment]
Hmm just tried that now after a fresh boot :/ Still not working even after force closing.

**Comment by TessellatedGuy** [comment]
Working perfectly after flashing new update. Issue closed.....

**Comment by sirleon23** [comment]
I report the SAME problem, I ve done everything 
Clean install
Force close, delete data and cache 
Root access (su and privacy guard can confirm) 
But I can see only a empty page with icons on the top (if I try to change something about configuration,Or simply icon of stweaks.. This is impossible!)so few features appear in reality don't work. 
How can I fix it?

**Comment by AntaresOne** [comment]
@sirleon23 did you try to wipe /data? It will fix your issue which in front of 34k+ downloads of the 25/7+17/8 builds has been reported only two times... This is surely caused by something did by the user like installed some app which broke how the software works
