### ISSUE TITLE
Phone becomes unresponsive while using Bluetooth

### ISSUE THREAD

**Issue by darthchile** [JDCTeam/issue_tracking_cm#12]
Mainly I see this problem after opening whatsapp, but with any notification as well. The notification sounds freezes the volume handler (?) and the phone becomes unresponsive, but only while on bluetooth, symptom is not present while using wired headset. 
Using build 20150701

**Comment by AntaresOne** [comment]
Do you have a log for this?

**Comment by darthchile** [comment]
I think I can generate some using STweaks if you tell me how

**Comment by darthchile** [comment]
Javier Gonzalez

Mobile: +420 733710912
E-mail: darthchile@gmail.com
Think before you print.

**Comment by darthchile** [comment]
After update to new release (clean install, all as instructed in xda) the phone still becomes unresponsive while on Bluetooth (any device) and I chat using whatsapp. I can generate a log using STweaks widget because nothing responds at that point. How do I set the logging to capture this?

**Comment by AntaresOne** [comment]
@darthchile did you update to the latest available build? it has various fixed stuff inside. If you still experience the same behavior please reopen this, thank you.
