### ISSUE TITLE
Bluetooth share has stopped working

### ISSUE THREAD

**Issue by TessellatedGuy** [JDCTeam/issue_tracking_cm#14]
Using build v20150701. Bluetooth does not turn on and when I try to, it just pops up bluetooth share not working.

**Comment by TessellatedGuy** [comment]
Yes I have seen the closed bluetooth share issue.

**Comment by TessellatedGuy** [comment]
Yes I have formattedto f2fs as well.

**Comment by pace6666** [comment]
Same with Clean version v20150701 F2FS. I saved logs.

https://www.dropbox.com/s/4ov4uwuhnxgbloj/2015-07-05_09.58.zip?dl=0

**Comment by AntaresOne** [comment]
Baseband version?

**Comment by TessellatedGuy** [comment]
My baseband version:
I9505XXUHOB7

**Comment by arnauld69** [comment]
Same problème every minute.
My baseband is : I9505XXUEMKF

**Comment by pace6666** [comment]
Now Bluetooth share is working for me with v20150725

I tried things from XDA comments. Dont judge me but this annoying problem is gone and my S4 is a rocket now!!

-Wiped and converted to F2FS
-Flashed clean ROM
-Rebooted and ran setup
-Enabled bluetooth
-Rebooted to recovery and flashed ROM without wipe
-Flashed open gapps
-Rebooted and that's it.

**Comment by TessellatedGuy** [comment]
Yep mine's working after clean flashing the new update and all's fine! I'm just gonna keep this open as someone else still haven't fixed it, or should I close this issue?

**Comment by smashtie** [comment]
Still fails for me on 20150725, and I've done all the steps mentioned by pace6666 above.  I have a tombstone.

Phone model: GT-I9505
Baseband version: I9505XXUH0D7
ROM version: 20150725
GApps Package: open gapps arm 5.1 aroma 20150726 with most apps installed (log below)

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

See here for logcat, tombstone and gapps install log:
https://www.dropbox.com/sh/htr08i57h1o8szs/AACIhHyKP-NvG2Pwt72IoeX3a

**Comment by pace6666** [comment]
Still working great today... For my part if it can help for Smashtie:

I had problem to flash 1st time, I got permssion failure but I tried to flash again immediatly and it worked

Phone model: SGH-M919V
Baseband version: M919VVLUGOC4
ROM version: OptimizedCM-12.1-20150725
GApps Package: open_gapps-arm-5.1-micro-20150726

**Comment by smashtie** [comment]
Repeated dirty flash of ROM and gapps.  No change.  Bluetooth audio also stuttering, even in performance mode.  Reading around leads me to believe this is really a CM12.1 issue.

Too bad for the blood pressure, so I'm afraid I can't use this as my daily driver.  Reluctantly I've switched back to a Samsung based 5.0.1 ROM (Imperium LL), and bingo, no more stutter, no more crashes, with the same modem/bootstrap.

**Comment by smashtie** [comment]
Just spotted your response on xda.  No I didn't try Awesome player in developer options.  Sorry.  I'll give it a go if I can find the time.

**Comment by AntaresOne** [comment]
@smashtie I'll wait for you about AwesomePlayer. Sorry for the slow answers, but we're on summer! :+1:

**Comment by darthchile** [comment]
I have an interesting behavior with this. On a cheap BT speaker, no issues. Using Plantronic C720: no issues. But when I use my Cardo Q1 BT headset (for motorcycle helmet) the music is like when you slow down a record just a little bit (under tone), and the musics skips and it is just crap and the BT share crashes.

**Comment by geedubess** [comment]
Same issue here (BT cannot turn on; Bluetooth Share crash popup); SPH-L720, OptimizedCM-12.1-20150725, L720VPUGOD2.

I installed a Samsung 5.0.1 stock ROM (everything worked fine), wiped system/data/cache and installed Optimized ROM (as well as gapps-aroma-5.1 in the same go). BT worked fine for me w/ the previous Optimized release.

Have tombstone/can easily reproduce. Am using Titanium Backup to freeze 'Bluetooth Share' so I don't get annoying popups for now!

**Comment by darthchile** [comment]
Tested the Cardo BT. No crashes after following pace6666's steps and enabling AwesomePlayer. However the audio still sounds "slow" and music skips using any player, youtube video/audio looses sync (audio is slower than video). Very annoying and just not functional to use. Let me know what you need before I flash another ROM.

**Comment by smashtie** [comment]
OK, I've restored this ROM, and I'm testing with AwesomePlayer.  So far the sound is good, no stutter, and it has reconnected and played a couple of times.  I'll let you know how it goes tomorrow.

**Comment by smashtie** [comment]
Looks like selecting AwesomePlayer has fixed it.  Two days with no bluetooth crash.  So yes, it's that NuPlayer.  If you can, please keep it open for a couple of days more, just to be sure, then feel free to close.

**Comment by smashtie** [comment]
Not quite fixed.  Much lower incidence, but it still crashed this morning.  Same bluetooth share has stopped message.  Reboot was required to get it back.

**Comment by seapython** [comment]
Same issue here (BT cannot turn on; Bluetooth Share crash popup keeps reoccurring); Galaxy S4 GT-I9505, OptimizedCM-12.1-20150725.

Started from a Samsung 5.0.1 stock ROM (everything worked fine), wiped system/data/cache and installed Optimized ROM, nothing else. Re-wiped data and cache again from TWRP 2.8.7.0, rebooted, no fix.
Backed out and returned to 5.0.1 stock for now.

**Comment by smashtie** [comment]
I've also returned to a 5.0.1 (GPE) and had no problems since.

**Comment by AntaresOne** [comment]
@everyone: please update to the latest build available. If you still experience issues reopen this.
