### ISSUE TITLE
Again no alarm clock after a night in charging (with 25th July build)

### ISSUE THREAD

**Issue by Kethav** [JDCTeam/issue_tracking_cm#15]
PHONE SPECS:
- Galaxy S4 I9505 (jfltexx)
- CyanogenMod-Version: 12.1-20150701-OPTIMIZED-jflte
- open_gapps-arm-5.1-micro-20150614
- Baseband: I9505XXUHOD7
- TWRP Recovery v2.8.7.0
- F2FS File System
- Clean Install : YES

DESCRIPTION
Hello,
I've flashed the 20150701 build the last week and during these days it's the second time the alarm clock doesn't sound in the morning.

When I look at the screen I see the alarm animation but no sound comes from the phone... 

The first time after reboot it was working as usual.
This time I rebooted but didn't check for alarm working or not because after the reboot the interface changed to Trebuchet even if "Start applications now" was selected.
I tried switching between Trebuchet and "Start application now" but the interface got stuck at "Trebuchet".

A second reboot fixed the issue and "Start application now" finally appeared.

I don't know how to extract the log, if you can help me to extract it, I will be happy to post it here

**Comment by Kethav** [comment]
Today I had the same issue as yesterday: no sound on alarm clock.

This time I checked for audio and found that no sound came from the phone, even with other applications like "Music" or anything else (also system sounds weren't avaiable).

Every evening, at around 9 p.m. I plug the device to the wall charger and leave it until the morning.
When I plug the device the sound is ok, while the following morning it doesn't work. (A reboot can fix it)

**Comment by Kethav** [comment]
Trying to pinpoint the problem I reminded that everytime I had the problem, the phone was plugged when remaining power was well BELOW 15% (and I set that under 15% the system goes to battery save mode).

So, yesterday evening I plugged the phone to the charger with the remaining charge well above 15% (at about 40%).

This morning the alarm clock worked well BUT....

I faced another problem (I will open another topic): when I receive a call the other part hears a constant loud whistle (it sounds like a constant very loud dial tone).

See my other topic for more details on this new problem.

**Comment by AntaresOne** [comment]
Hi mate,
can you try to update to the latest build available **20150725**?

The 1st July one is nothing more than a test, therefore should not be installed anymore...

**Comment by Kethav** [comment]
Yes, I already done that (a couple of days ago) and at the moment the alarm clock is working... never had the issue with the new build.

I'll wait for a week or so and then I'll report if the problem is solved using the new release.

**Comment by Kethav** [comment]
This morning I noticed the same issue with the last build.... this time system sounds were working but the alarm clock didn't... not sure if it was a configuration problem... yesterday the alarm clock during the day worked well (I used it for a reminder in the afternoon and it worked).

I have to say that yesterday evening I turned off the phone and let it charge (to refresh the battery), then I switched it on before going to sleep (while still plugged in) and left it on the desk...
This morning the alarm clock didn't ring...

It seems to me that there's something weird about power plug and alarm clock... but I could be wrong...

**Comment by AntaresOne** [comment]
@Kethav any update on your issue? did you try the most recent build? I don't have alarm issues

**Comment by Kethav** [comment]
Hello,

actually I changed the phone due to battery issues so I don’t use the Galaxy S4 any more.

Da: AntaresOne [mailto:notifications@github.com] 
Inviato: mercoledì 28 ottobre 2015 22:05
A: JDCTeam/issue_tracking_cm issue_tracking_cm@noreply.github.com
Cc: Kethav kethav@gmail.com
Oggetto: Re: [issue_tracking_cm] Again no alarm clock after a night in charging (with 25th July build) (#15)

@Kethav https://github.com/Kethav  any update on your issue? did you try the most recent build? I don't have alarm issues

—
Reply to this email directly or view it on GitHub https://github.com/JDCTeam/issue_tracking_cm/issues/15#issuecomment-151989618 .  https://github.com/notifications/beacon/AM0wHov52eqYUI4g7FaO1zVo0GKjF_mYks5pAS_mgaJpZM4FdVi0.gif 

---

Nessun virus nel messaggio.
Controllato da AVG - www.avg.com http://www.avg.com 
Versione: 2016.0.7163 / Database dei virus: 4455/10899 - Data di rilascio: 27/10/2015

**Comment by Soulfinger82** [comment]
My Clock had started to crash every time i opened it to edit the alarm.
Was just about to do a clean install of the rom when i realised i hadent tried to clear the cache and data in the clock app which solved the problem. Just had to set up all alarms again but thats a small sacrifice compared to a fresh installation of the rom :P
