### ISSUE TITLE
12.1-20150701-OPTIMIZED-jflte: "Root access: ADB only" doesn't work

### ISSUE THREAD

**Issue by ralfbergs** [JDCTeam/issue_tracking_cm#16]
I had set `Root access` to `ADB only`, but I couldn't get root from `adb shell`. As soon as I switched to `Apps and ADB` I could immediately get root.

**Comment by AntaresOne** [comment]
Hi,
when you set "ADB only" you should do **adb root** before issuing your commands. After it you can also open a root shell by **adb shell**

If you set "Apps and ADB" you don't need to do **adb root**
