### ISSUE TITLE
Gallery app cannot show Facebook photos.

### ISSUE THREAD

**Issue by raczrichardd** [JDCTeam/issue_tracking_cm#17]
The default gallery app doesn't show downloaded photos from facebook. It shows that I rename fb_img.. to img...

**Comment by AntaresOne** [comment]
Hi,
which Facebook version are you using? Default gallery here correcty shows downloaded Facebook pics, I have 179 right now

**Comment by B--B** [comment]
No answer and photos works for AntaresOne, can be closed
