### ISSUE TITLE
mediaserver crash

### ISSUE THREAD

**Issue by snifer1981** [JDCTeam/issue_tracking_cm#19]
/system/bin/mediaserver crash. I can reproduce it by sending a text message in Whatsapp.
25 July version.

Tombstone: http://pastebin.com/6rae2RVf

**Comment by AntaresOne** [comment]
Hi,
I see you're on NUPlayer. Can you try to go in Settings->Developer options and choose "Enable AwesomePlayer"? Then retry. Thanks for the report, have a nice night!

**Comment by snifer1981** [comment]
Hi, using AwesomePlayer doesn't make mediaserver crash, but description says it's obsolete or deprecated (i'm translating from spanish), so maybe i'm breaking other things. I'm using AwesomePlayer since last few days and I haven't seen new crashes.

Do you know if it's specific to this ROM or should it be fixed in CM? May be AwesomePlayer should be enabled by default as a temp fix.

BTW, I'm on GMT-3, so it's afternoon here :)

**Comment by AntaresOne** [comment]
@snifer1981 any mediaserver issue has been fixed for the 22/10 build. I'm closing this. :)
