### ISSUE TITLE
Phone call errors.

### ISSUE THREAD

**Issue by torbenj** [JDCTeam/issue_tracking_cm#2]
A few days ago I noticed that I'm unable to speak or listen to anyone while phone calling/getting phone called. It seems that my smartphone is only outputting/sending voice data every 4-5 seconds. In the remaining time there is no sound. So I can only hear the caller every 4-5 seconds and the other way around.
Unfortunately this issue remains after updating to the latest version (that I used now to replicate and report this issue).

I've attached a link to a gist containing the logcat logs for this issue.

**I noticed that there are at least two messages that occur regularly:**
1.(occurring anytime, not only while replicating the issue)

<pre>
I/auditd  (10484): Starting up
E/auditd  (10484): Failed on audit_set_pid with error: Protocol not supported
I/auditd  (10484): Exiting
</pre>

2.(I think this is the main issue)

<pre>
[...]
W/AudioSystem(20721): AudioFlinger server died!
[...]
</pre>

<pre>
[...]
W/AudioSystem(20721): AudioPolicyService server died!
[...]
</pre>

These "server died" messages occur only when calling (at least in my observations.
#### Specs:
- Galaxy S4 I9505 (jfltexx)
- Android 5.1.1 (Version from 1.7.2015)
- CyanogenMod-Version: 12.1-20150701-OPTIMIZED-jflte

The error occurred with an older version (I think it was 5.0.1 OPTIMIZED-jflte). As far as I know it didn't happen in any 4.x version.
_I'm also using DSP Manager 5.0.8 if this could be an issue_
#### Logs:

https://gist.github.com/TorbenJ/48da6f0003b8d02f4bfd

Would be great to get any feedback on this.

**Comment by AntaresOne** [comment]
Hi,
Thanks for the report. Can we know your baseband version?

**Comment by torbenj** [comment]
Yes of course.
My baseband version is I9505XXUHOD7

**Comment by torbenj** [comment]
I recently flashed cm12.1-20150711-NIGHTLY-jfltexx onto my phone to check if it might be a problem with CM itself but it isn't. My issue doesn't occur on this nightly build of cm12.1.

**Comment by torbenj** [comment]
Seems to be fixed with the latest version OptimizedCM-12.1-20150817

**Comment by torbenj** [comment]
Unfortunately I was wrong.

**Comment by AntaresOne** [comment]
@TorbenJ can't reproduce this here, at least with 22/10 build.
