### ISSUE TITLE
Your system dont have WGET from my kernel

### ISSUE THREAD

**Issue by mrwogu** [JDCTeam/issue_tracking_cm#20]
SPECS
- Galaxy S4 I9505 (jfltexx)
- CyanogenMod-Version: 12.1-20150725
- open_gapps-arm-5.1-micro-20150726
- Baseband: I9505XXUHOE3
- TWRP Recovery v2.8.7.0-F2FS
- F2FS File System
- Clean Install : YES

When i am trying to install / update Ad blocker (using STweaks,) i got this message

> Your system dont have WGET from my kernel, reinstall my kernel

**Comment by toprekmusic** [comment]
+1 here

**Comment by gllmhyt** [comment]
Same here.

**Comment by AntaresOne** [comment]
Hey guys,
There was an issue where the system didn't grep WGET binary while building. Please wait for the next build where it will be fixed or flash [this](http://d-h.st/8Nvq) zip, thanks to @hawkerpaul
