### ISSUE TITLE
MMS not working with Vodafone DE

### ISSUE THREAD

**Issue by sebastian-noc** [JDCTeam/issue_tracking_cm#22]
My colleague and me did a clean install on our jfltexx and are facing the same issue now: we can not send / recieve MMS.

```
Galaxy S4 GT-I9505
CyanogenMod-Version: OptimizedCM12.1-20150725
open_gapps-arm-5.1-micro-20150726
Baseband: I9505XXUGNE8
TWRP Recovery v2.8.7.0-F2FS
F2FS File System
Clean Install : YES
```

We use the APNs, provided with your ROM.
When the mobile is connected to a WiFi network, we can send / receive MMS.
When we turn off WiFi, the phone switches to LTE, until here everything is fine.
When now a MMS should be send / received, the mobile data connection gets down and we can not send / revive any data like webpages etc and the MMS is not send / received as well.

What can I to do give you more logs / debug for analysis?

Thanks and kind regards
Sebastian

**Comment by mrwogu** [comment]
- 1
  same here with Play Mobile (PL)

**Comment by AntaresOne** [comment]
Hi there,
please check APNs, the default one which makes the Internet navigation working must also have "mms" in APN type

**Comment by mrwogu** [comment]
@AntaresOne i'm sure that my APN configuration is correct (the same works on my SGS4 branded android).

**Comment by sebastian-noc** [comment]
I compared the configuration of the APN with the orginal Android on the Galaxy S2 from my wife and the Galaxy S6 with original Android @ work. The configuration is the same, nevertheless, it does not work with my OptimizedCM12.1-20150725.

I tried to add "mms" at the default APN.
It was APN type "default,supl" before and I changed it to "default,supl,mms".
After that, when trying to send an mms, I get a message like "no APN configured" (the orig. message is german, but that is the message).

Here my current APN config which work fine for LTE, but not with MMS:
First APN (all fields not mentioned have no value)
Name: VF DE WEB
APN: web.vodafone.de
MCC: 262
MNC: 02
Authentication: None
APN Type: default,supl

Second APN (all fields not mentioned have no value):
Name: VF DE MMS
APN: event.vodafone.de
MMSC: http://139.7.2.1/servlets/mms
MMX Proxy: 139.007.029.017
MMS Port: 80
MM: 262
MNC: 02
APN Type: mms

Can you please post the values of your APNs, if they work fine?

Please note: with all APN set to default, I do not get a mobile internet connection, only WiFi networks.

Thanks a lot.

**Comment by B--B** [comment]
Fixed https://github.com/JDCTeam/android_device_samsung_jf-common/commit/3a9de49970ce31abcb6e6ed0afde632ecf9ed01e
