### ISSUE TITLE
Data stop working

### ISSUE THREAD

**Issue by ravv7** [JDCTeam/issue_tracking_cm#23]
After some time when phone is locked and not used the mobile data stops and reboot is necessary.
I9505
Carrier VodafoneCZ
LTE preffered
ROM OptimizedCM-12.1-20150725, Clean flash
Baseband I9505XXUHOF2
no changes in kernel etc.

**Comment by ravv7** [comment]
Looks solved by reflashing modem FW

**Comment by ravv7** [comment]
So not... Data stopped again.  
This time restarted with switch on/off airplane mode

**Comment by AntaresOne** [comment]
Hi there,
do you have any logcat for that mate?

**Comment by ravv7** [comment]
It had not happened again from my comment here. It is not often. 
I am not so expert, so write me, please, where is the log so I can send it. 
Btw - 15 mins ago I got phone block and selfreboot when configured Handcent SMS app...

**Comment by ravv7** [comment]
So It happened again after 3 days... again, just switching on/off of airplane mode helped to get data back
here is saved log http://mujweb.cz/rav/cm/
Phone was just on table without any using for some time, along weather widget update data stopped about 1 hour before I recognised it (last update 19:20, logged cca 20:30)

**Comment by ravv7** [comment]
It happened again this night during charging at about 2:00am, found morning at about 9am.

**Comment by ravv7** [comment]
It happened every night, while mobie is longer time not used

**Comment by ravv7** [comment]
it happen often and often, every 2-3 hours now... Think I will reflash clean again or other ROM

**Comment by ravv7** [comment]
So final:
After clean instalation new (OTA failed and disrupted lot of functions) v2 - 20150817 first worked well but after 2 days started to lost LTE data, or if in area where was no LTE it did not changed to 3G or Edge and data was lost. Maybe this was the reason from start - do not switch to 3G/2G data if lost 4G.

Now installed clean cm-12.1-20150825-NIGHTLY and all works well. Just missing STweaks, data transfer speed on status bar... :(
