### ISSUE TITLE
Galaxy s4 Crash 

### ISSUE THREAD

**Issue by ghost** [JDCTeam/issue_tracking_cm#24]
I have Crashs where the Smartphone restarts istelf. 
Happens Most of the Time while playing the game beast towers. Also happened while using the Google camera app. I havent changed any settings and did a clean install with 25th july update. Please let me know how to provide logs so i can help solving the Problem. 

Have a nice Day

**Comment by AntaresOne** [comment]
Hello,
you can put a STweaks widget in home screen to take a log when you are experiencing an issue. For system crashes the best thing to see is the last_kmsg, this file survives a single boot only before being cleaned.
- System crash
- Kernel log is saved
- Autoreboot
- Once you see the home screen, navigate to /proc with a root file manager or through ADB and save last_kmsg

**Comment by ghost** [comment]
Thanks for the reply. 
As soon as it happens the next time i will upload the log.

**Comment by ghost** [comment]
Once again it crashed while playing beast towers. 

Here is my last_kmsg:
http://www.xup.in/dl,13466486/last_kmsg

**Comment by ghost** [comment]
I can now say that it happens every Time i play beast towers. 

I opened the last kmsg and the last line says something with Kernel.

**Comment by ghost** [comment]
Seems like nobody is really interested in this. I now got problems with WiFi and my mobile Data doesn't work at all.

I'm switching back to official. 

Good Luck to you guys

**Comment by smeroni68** [comment]
It is August and we are  in vacation. Good luck to you and enjoy official or what ever rom you like to use.

**Comment by AntaresOne** [comment]
@yaboybigT

It is not that nobody is interested in this, but since we're on vacation a bit more patient is always preferred... Remember that we (especially me) are  not your workers, we're not earning anything from users. Then why say "Seems like nobody is interested in this"? 

For the mobile data issue check your APN, you didn't say your device variant. For the WiFi what kind of issue?

**Comment by B--B** [comment]
These report has been made before all mm/slab merges in kernel and should be fixed now, i close this due to huge changes in kernel, if happens again open a new bug
