### ISSUE TITLE
S4 i9505 google play services crash

### ISSUE THREAD

**Issue by chrisgj19** [JDCTeam/issue_tracking_cm#25]
Google play services keeps crashing on the latest update. the previous versions of the rom dint have any such issues. So now even play store doesnt work.

**Comment by ghost** [comment]
Did you install opengapps via Aroma? After doing this i had the Same Problems. I reinstalled clean rom and micro gapps and now the Problem is gone.

**Comment by AntaresOne** [comment]
@chrisgj19 you didn't do a clean install, it is required... Please do it and your FC will disappear, not an issue, closed
