### ISSUE TITLE
Bluetooth & Wifi triggers in system profiles are disappearing after reboot

### ISSUE THREAD

**Issue by mrwogu** [JDCTeam/issue_tracking_cm#26]
SPECS
- Galaxy S4 I9505 (jfltexx)
- CyanogenMod-Version: 12.1-20150725
- open_gapps-arm-5.1-micro-20150726
- Baseband: I9505XXUHOE3
- TWRP Recovery v2.8.7.0-F2FS
- F2FS File System
- Clean Install : YES
- Reboot: YES
- System modification: NO
- Another kernel: NO
- Xposed framework: NO

Hello, I configured my system profiles with wifi & bluetooth triggers (activate profile A when bluetooth device will connect, activate profile B when bluetooth device or wifi device will disconnect, activate profile C when wifi device is connect). Everything works fine until I reboot my smartphone. After reboot - all my bluetooth triggers and wifi (only disconnect) triggers have gone. 

To sum ap:
After reboot - all system profile triggers (except "on connect wifi") have gone away.

The same issue was on previous release12.1-20150701-OPTIMIZED-jflte.

**Comment by AntaresOne** [comment]
Hello,
thanks for the report. I will try to reproduce myself and give further info here. Have a nice night! :+1:

**Comment by AntaresOne** [comment]
@mrwogu if you are still around please update to the 22/10 build, I did not have success into reproducing.
