### ISSUE TITLE
[STweaks] Busybox

### ISSUE THREAD

**Issue by gllmhyt** [JDCTeam/issue_tracking_cm#27]
My device configuration:
- Galaxy S4 I9505 (jfltexx)
- CM: OptimizedCM-12.1-20150725-jflte
- GApps: open_gapps-arm-5.1-pico-20150730
- Baseband: I9505XXUHOB7
- TWRP Recovery v2.8.7.0-F2FS
- F2FS File System

Steps to reproduce:
- Launch STweaks
- Go to "Other"
- I think changing the GPS region doesn't change the gps.conf file, maybe related
- Update Time

Error:
- "Your BusyBox is not supported! Update to latest"

**Comment by AntaresOne** [comment]
Hi,
thank you for the report. I was able to reproduce it myself, issue addressed.

**Comment by snifer1981** [comment]
gps.conf is updated in my case, I've set it to South America. Can OP check if it's really happening, and which option?

Update time error is reproducible here too.

**Comment by AntaresOne** [comment]
@snifer1981 closing this as reported working on the most recent builds
