### ISSUE TITLE
Roaming problem

### ISSUE THREAD

**Issue by nbc** [JDCTeam/issue_tracking_cm#28]
Hello,

```
Phone model: ex. GT-I9505
Baseband version: ex. I9505XXUEMKF
ROM version: 20150725
GApps Package: open_gapps-arm-5.1-nano-20150726

Did you do a clean install for the currently installed build? yes (factory reset in TWRP)
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no
```

Each time I try send an MMS, I loose data connection (exclamation mark on the status bar) and I need to turn on and off airplane mode to get it data connection up.

I'm not sure if it's normal but while Data roaming is enabled in Mobile network settings, "About phone -> Status -> SIM status -> Roaming" is at "not Roaming"

logcat : https://dl.dropboxusercontent.com/u/10809938/galaxy.log

**Comment by mrwogu** [comment]
Same here.
The same is when someone sens mms to me. Losing data connection every 2-3 minutes until i remove thread with mms.

**Comment by AntaresOne** [comment]
Please edit your APN (first check if mobile data connection lets you surf on the net) adding **mms** to APN type
