### ISSUE TITLE
Bluetooth share

### ISSUE THREAD

**Issue by pace6666** [JDCTeam/issue_tracking_cm#3]
Keep telling "Bluetooth share" stopped

**Comment by jdgarcia1381** [comment]
I solved this problem changing file system to f2fs.

**Comment by pace6666** [comment]
I rolled back to older version yesterday, then I changed file system to f2fs today and retried last version then everything's fine now!

**Comment by jdgarcia1381** [comment]
I have the latest version (1 July) with f2fs and it works perfectly. I think you can close this issue :)

**Comment by pace6666** [comment]
No... Still having the same issue twice/day.  I have to reboot and then I'm OK for few hours.  Because I use my phone with running app. I'll ne forced to uninstall.  I saved log files to https://www.dropbox.com/s/4ov4uwuhnxgbloj/2015-07-05_09.58.zip?dl=0
