### ISSUE TITLE
Limited contacts features

### ISSUE THREAD

**Issue by tranceboy** [JDCTeam/issue_tracking_cm#30]
Contacts are not like the stock firmware. Its so simple you can't even edit them or group them or watch their Whatsapp or other app links !

**Comment by tranceboy** [comment]
Also you can search by number if only start typing from the first digit !

**Comment by smeroni68** [comment]
This is CM and AOSP contact dialer... and is not an issue for github...

**Comment by AntaresOne** [comment]
@tranceboy 

![screenshot_2015-08-04-13-03-11](https://cloud.githubusercontent.com/assets/5553545/9059328/53b18690-3aa9-11e5-9a63-5183f8d6d1c6.png)
![screenshot_2015-08-04-13-03-21](https://cloud.githubusercontent.com/assets/5553545/9059330/5a5af2a6-3aa9-11e5-91f1-3e4c747b6fa4.png)

And for who has other stuff like Google+, WhatsApp etc I can see links, open them. **No issue here**, closing
