### ISSUE TITLE
GT-I9507 sensors not available after a UI/VM crash and reboot

### ISSUE THREAD

**Issue by tmc-au** [JDCTeam/issue_tracking_cm#31]
Devs, thank you for your hard work to bring us an optimized ROM.

Unfortunately I have run into an issue that **appears** to be two related related issues. I can be complete wrong and I might be seeing two separate issues at once.

**System:**
ROM is your Stable #1 release. 
My phone is Galaxy S4 GT-I9507, with baseband I9507XXUFOA1 

**Symptoms:**
System boots and comes up. If the screen rotation is enabled, it will reboot the VM (no hardware logo, just the CM logo) after a random time.

After the system reboots, all the sensors go into an odd mode, where they report their presence (for example via the  com.snipesense.androsensor app) but no data is gathered form the sensors, as if they were not sending any. At the same time the adaptive screen brightness control, and sometimes screen rotation fails.

Also what appears to be happening is that some of the power control code appears to fail, and the phone runs hot and drains battery very quickly.

Last good known ROM that correctly for sensors and power control was CyanogenMod 12.1 build _12.1-20150706-nightly-jfltexx_

Your ROM and all the CyanogenMod nightly jflte/jfltexx ROMs I have used since have the same set of issues: Sesors either do nit work, or sensors work but appear to cause random UI/VM restarts.

**Comment by smeroni68** [comment]
We checked with Alucard, and GT-I9507 is not included on variant management (this due to lack of source code)
-   SGH_I337,
-   SPH_L720,
-   SGH_M919,
-   SCH_R970,
-   SCH_I545,
-   GT_I9505,
-   GT_I9295,
-   SHV_E300,
-   SGH_N045,

Probably in the next days, Alucard will modify the kernel and will build a version to be tested... and you are the tester... please **write here your email** where We can send you the test kernel...

In case it will not work, you can just flash back the rom without any wipe, and you will have back the stock kernel...

Regards

**Comment by smeroni68** [comment]
Sent a PM on your XDA account with link for test kernel... let us know the effect!!

**Comment by tmc-au** [comment]
Hi Guys. 

Kernel obtained. I will do a test today, and see how stable it is. I will report my results here  as they become available. 

Tomasz

**Comment by tmc-au** [comment]
**The kernel test results** 

**Platform:** GT-I9507 ( aka JFTDDXX) with CM12.1 20150806-nightly-jfltexx and the alucard test kernel.

_**Note:** This phone is my main phone, so I can't easily chop and change the ROMs without loosing some apps that require some though to re-setup (google authenticator for one)_

**Tests/Observations**
- UI is stable. No more spontaneous reboots.
- Sensors work and do not lock up - acceleration, gyroscope, proximity, light level, temp, barometer, magnetometer, and humidity
- NFC works
- WiFi 2.4GHz and 5GHz works
- WiFi hotspot works
- Bluetooth hotspot work
- Bluetooth Audio - call headset  - works
- 3G data works
- LTE/4G data works, but phone seems less agressive it attaching to LTE. Could be local conditions
- Ambient light display adjustment works
- GPS works
- Battery life is OK, but I am not sure that it could be any better. GPS chipset appears very power hungry and was most of the day.

**Overall result:** Success.  This kernel solved all the issues I have been experiencing. It proves that the difference between I9505 and I9507 is simply the modem/radio - I9507 does LTE-TDD and LTE-FDD signalling, where I9505 is LTE-FDD only.

**Comment by smeroni68** [comment]
Thanks for testing... Dev is handling the modifications to support finally 9507 and probably 9508 too...

Use the kernel you got over the CM roms... on next JDC Team version it will be integrated...

Regards

**Comment by tmc-au** [comment]
Glad to be of assistance.
