### ISSUE TITLE
S4 Crash/Booterror/Power Button/Display Lock

### ISSUE THREAD

**Issue by PePeMoke** [JDCTeam/issue_tracking_cm#32]
Hi.
I know you need logs and not only the issue.
I am a bit confused about capturing a log in Stweaks..
Is it "Bug report for Kernel" or under "other" and then "Android Logger"?

**Comment by PePeMoke** [comment]
Ok I've got it now.
Found the STweaks widget and will send you a log when it happens again.

**Comment by AntaresOne** [comment]
Waiting for the log, thank you in advance

**Comment by PePeMoke** [comment]
The last_kmsg file says it's empty. "Remote file not found"
I can only send you the alucard_debug.zip

https://www.dropbox.com/s/842dlm53s7gwzt1/alucard_debug.zip?dl=0

**Comment by PePeMoke** [comment]
Everytime it happens the file last_kmsg is there, when navigating to it with total commander, but when i try to upload it, it says "empty file"..
What can I do? Any tips?
Just answer when you are in the mood, it is not that urgent.
Enjoy your vacation! :)

**Comment by PePeMoke** [comment]
Do you got an idea for this issue with the empty last_kmsg?

**Comment by smeroni68** [comment]
Empty last_kmsg means not a kernel panic or stuff related... install Syslog or Catlog from market and use one of these apps to get full logs. Thanks

**Comment by PePeMoke** [comment]
https://www.dropbox.com/s/bbb193p8cgx3svv/2015-09-16_18.35.zip?dl=0

**Comment by PePeMoke** [comment]
Thanks. Senat you a dropbox link.
The Problem did not accure for a while now.

**Comment by PePeMoke** [comment]
Is there any useful information in the log regarding the issue I described, or does anything seem to be normal?

**Comment by PePeMoke** [comment]
Did not happen since I flashed new bootloader.
Might been that..
I close this issue until it turns up again.
And the next build is near so..

**Comment by PePeMoke** [comment]
https://www.dropbox.com/s/kicxsfz7lk9l7xg/last_kmsg?dl=0

Issue is back again.
Last_kmsg is right here.
Plesse let me know what is wrong.

**Comment by PePeMoke** [comment]
Could someone help me please?..
Is it the right thread??

**Comment by PePeMoke** [comment]
??
