### ISSUE TITLE
System UI has stopped

### ISSUE THREAD

**Issue by eddloschi** [JDCTeam/issue_tracking_cm#33]
While watching an Instagram video the phone froze. Nothing responded for a while. Then softkeys started vibrating when touched, but the image being displayed was still frozen. After that, the **system UI has stopped** dialog appeared.
The problem with this issue is that it is difficult to replicate. It happened before (not in the same scenario), but that was the first time I captured logs, which I'm not sure will be helpful. The only thing that stood out for me was the huge amount of _CursorWindow_ errors in the logcat, but I'm not sure what it is and if it's related to the freeze followed by system UI FC
- model: **jfltexx**
- baseband: **VJUHOF2**
- ROM version: **20150725**
- GApps: **TK GApps Stock 20150802**
- **clean install**
- **no reboot**
- **no system mods**
- **original Alucard kernel**
- **no xposed**
### Logs:
- logcat: https://www.dropbox.com/s/8w2kog17tmdx7sc/2015-08-06-09-41-22.txt?dl=0
- dmesg: https://www.dropbox.com/s/1wynuo2gjhpr45b/dmesg.txt?dl=0

**Comment by AntaresOne** [comment]
@eddloschi please update to the latest build available, not a single issue since 6 days.
