### ISSUE TITLE
No LTE on SPH-L720

### ISSUE THREAD

**Issue by hal7df** [JDCTeam/issue_tracking_cm#34]
Every build I've tried since Optimized CM12 (5.0.2) build 20150314 has had mobile network issues. More recent builds have had success with 3G, but 3G speeds (at least with Sprint) can be rather slow, and LTE would be a nice thing to have. (This issue is literally the only thing keeping me from upgrading)

Whenever the device finds an LTE network, the "Mobile network state" under Settings > About > Status > SIM Status gets stuck on "Connecting".

I have a FreedomPop phone if it matters. I have tried changing APNs to no avail.
- **Phone model**: jfltespr
- **Baseband**: L720VPUFNG2
- **ROM Version**: 20150725
- **GApps package**: Open GApps nano 20150809
- **Clean install**: yes
- **Rebooted**: yes
- **System mods**: no
- **Kernel**: 3.4.108-Alucard-PWR-CORE-GCC6 (default)
- **Xposed**: no

[Logcat](https://gist.github.com/hal7df/5ca24ba777050b195a75)

**Comment by AntaresOne** [comment]
@hal7df a lot of things changed from that, can you try to update to the latest build available? reopen this if you still have that issue. Thank you

**Comment by hal7df** [comment]
OK, I clean flashed the 20151022 build and still no luck... Now, the phone doesn't even appear to try to connect to the LTE network, the status message just says "Disconnected". Changing APNs doesn't do anything. 3G and everything else works like a charm, though.
