### ISSUE TITLE
Bluetooth does not working 

### ISSUE THREAD

**Issue by Dwoogi** [JDCTeam/issue_tracking_cm#35]
I cant turn on bluetooth tho, when i try to do it the error appears and wi fi stops working. To get back my wi fi i must do factroy reset

**Comment by Dwoogi** [comment]
Phone model: GT-I9505
Baseband version: ex. I9505XXUFNC4
ROM version: ex. 20150725
GApps Package: Open GApps [type-full] [date] 

Did you do a clean install for the currently installed build? yes 

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? No
Did you install Xposed framework? yes/noPhone model: ex. jfltexx or GT-I9505
Baseband version: ex. I9505XXUHOD7
ROM version: ex. 20150719
GApps Package: CM GApps [date] or Open GApps [type] [date] or Slim GApps [type] [date] ex. Open GApps Micro 20150719

Did you do a clean install for the currently installed build? yes or no

Did you reboot after having the issue? yes/no
Did you do any system modification? yes: [mod]/no
Did you flash another kernel? yes/no
Did you install Xposed framework? no

**Comment by justmwa** [comment]
Got the issue right at start without doing anything: bluetooth sharing stopped working. I had it turned off at last and everything was smooth up until I mistakenly switched it back on, now it's draining the battery and it slows the phone big time.. I need to figure a way to have it off at boot!
I have no issues with WiFi though.

Phone model: GT-I9505
Baseband version: I9505XXUHOF2
ROM version: 20150725
GApps Package: Open GApps pico 20150809
Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

I/bt_hci_bdroid( 8267): init
I/bt_vendor( 8267): init
I/bt_vnd_conf( 8267): Attempt to load conf from /etc/bluetooth/bt_vendor.conf
I/bt_vnd_conf( 8267): vnd_load_conf file >/etc/bluetooth/bt_vendor.conf< not found
D/bt_userial( 8267): userial_init
I/bt_userial_vendor( 8267): userial vendor open: opening /dev/ttyHS0
I/bt_userial_vendor( 8267): device fd = 61 open
D/bt_userial( 8267): Entering userial_read_thread()
W/bt-btu  ( 8267): btu_task ignore evt 0001 while pending for preload complete
I/bt_hwcfg( 8267): bt vendor lib: set UART baud 3000000
I/bt_hwcfg( 8267): bt vendor lib: loading prepatch /vendor/firmware/bcm4335_prepatch.hcd
D/bt_hwcfg( 8267): Chipset BCM4335A0
D/bt_hwcfg( 8267): Target name = [BCM4335A0]
D/bt_hwcfg( 8267): Target name = [BCM4335]
I/bt_hwcfg( 8267): Found patchfile: /vendor/firmware/bcm4335_prepatch.hcd
I/bt_hwcfg( 8267): bt vendor lib: set UART baud 115200
D/bt_hwcfg( 8267): Settlement delay -- 100 ms
I/bt_hwcfg( 8267): Setting fw settlement delay to 100
D/ConnectivityManager(13423): getMobileDataEnabled()+ subId=1
D/PhoneInterfaceManager( 1908): [PhoneIntfMgr] getDataEnabled: subId=1 phoneId=0
D/PhoneInterfaceManager( 1908): [PhoneIntfMgr] getDataEnabled: subId=1 retVal=true
D/ConnectivityManager(13423): getMobileDataEnabled()- subId=1 retVal=true
D/BluetoothAdapterState( 8267): CURRENT_STATE=PENDING, MESSAGE = ENABLE_TIMEOUT, isTurningOn=true, isTurningOff=false
E/BluetoothAdapterState( 8267): Error enabling Bluetooth
E/bt-btif ( 8267): bte_ssr_cleanup
F/libc    ( 8267): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8285 (BluetoothAdapte)
I/DEBUG   ( 8173): property debug.db.uid not set; NOT waiting for gdb.
I/DEBUG   ( 8173): HINT: adb shell setprop debug.db.uid 100000
I/DEBUG   ( 8173): HINT: adb forward tcp:5039 tcp:5039
I/DEBUG   ( 8173): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   ( 8173): Build fingerprint: 'samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys'
I/DEBUG   ( 8173): Revision: '11'
I/DEBUG   ( 8173): ABI: 'arm'
I/DEBUG   ( 8173): pid: 8267, tid: 8285, name: BluetoothAdapte  >>> com.android.bluetooth <<<
I/DEBUG   ( 8173): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0

**Comment by justmwa** [comment]
By the way, I managed to work around the crash by "freezing" the app (com.android.bluetooth) with Titanium. Otherwise, the device was unusable! No bluetooth but everything else looks OK.

**Comment by pocci1992** [comment]
The rom in great, but with the version 20150817 the bluetooth does not work!

**Comment by AntaresOne** [comment]
@everyone update to the latest build available please.
@pocci1992 I used the bluetooth on that ROM build, not a single issue when transferring or receiving data.

If you still have issues please reopen this rather than making another one.
