### ISSUE TITLE
No IR blaster i-9505

### ISSUE THREAD

**Issue by garethrees20** [JDCTeam/issue_tracking_cm#36]
IR blaster is not functioning at all since the latest version 20150725.
IR was working for me in the previous version even using Peel/WatchON. 
I have tried several IR apps and no support on these either.

**Comment by garethrees20** [comment]
Sorry omitted the following :
Clean Install
Micro Gaps used
No custom kernels 
Latest TWRP with f2fs support
No xposed framework

**Comment by smeroni68** [comment]
Uncheck 'Use alternate ir command'...

**Comment by garethrees20** [comment]
Thanks for your response. Could you please be more specific where this
setting is located?
Some of the IR apps have this setting but it makes no difference.
Is there a global setting in the system somewhere?

**Comment by smeroni68** [comment]
Go on Settings... Advanced settings... "Use alternate ir command"... it is set as active... disable it.

**Comment by garethrees20** [comment]
Are you referring to a particular APP when you say to go to settings and advanced settings? In my android system settings I have no advanced settings.

**Comment by smeroni68** [comment]
Yes, is app related... no general setting on Android  (not yet let's say)...

**Comment by garethrees20** [comment]
Hi there,
I have found an APP which works when this option is disabled (previously
used software hadn't worked or caused reboots).  I am using Smart IR Remote
by AnyMote. It's about 8 euro's but works great, if you have any other
users having issues then I would recommend this one.
Thanks for your help!

**Comment by smeroni68** [comment]
You're welcome... Dev will code probably a switch on system to change the ir mode... but not soon...
