### ISSUE TITLE
Failed on audit_set_pid battery drain

### ISSUE THREAD

**Issue by roryjw** [JDCTeam/issue_tracking_cm#37]
Getting failed on audit_set_pid with error: protocol not supported, its draining battery while the screen is on. All good when screen off.

08-13 12:19:07.836 E/AudioTrack(679): AudioTrack::set : Exit
08-13 12:19:07.856 D/ALSADevice(230): route: devices 0x2 in mode 0
08-13 12:19:07.856 D/ALSADevice(230): No valid input device: 0
08-13 12:19:07.856 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _enadev value Speaker
08-13 12:19:07.856 D/ALSADevice(230): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Speaker
08-13 12:19:07.856 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value HiFi
08-13 12:19:07.856 D/alsa_ucm(230): Set mixer controls for Speaker enable 1
08-13 12:19:07.856 D/alsa_ucm(230): acdb_id 15 cap 1 enable 1
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_audio_cal, acdb_id = 15, path =  0
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_adm_topology
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_asm_topology
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_audtable
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_CAL
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_audvoltable
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
08-13 12:19:07.856 E/ACDB-LOADER(230): Error: ACDB AudProc vol returned = -8
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_afe_cal
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AFE_CAL
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> send_hw_delay : acdb_id = 15 path = 0
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_DEVICE_PROPERTY_SIZE
08-13 12:19:07.856 D/ACDB-LOADER(230): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
08-13 12:19:07.856 D/ACDB-LOADER(230): send_hw_delay id = 15 delay_num_entries = 1 result = 0
08-13 12:19:07.856 D/alsa_ucm(230): Setting mixer control: SLIM_0_RX Channels, value: Two
08-13 12:19:07.856 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: RX1
08-13 12:19:07.866 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: RX2
08-13 12:19:07.866 D/alsa_ucm(230): Setting mixer control: RX6 DSM MUX, value: DSM_INV
08-13 12:19:07.866 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 83
08-13 12:19:07.866 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 83
08-13 12:19:07.866 D/alsa_ucm(230): Setting multi value: RX5 Digital Volume
08-13 12:19:07.866 D/alsa_ucm(230): Set mixer controls for HiFi enable 1
08-13 12:19:07.866 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
08-13 12:19:07.866 D/ALSADevice(230): close: handle 0xb587a680 h 0x0
08-13 12:19:07.866 D/ALSADevice(230): open: handle 0xb587a680, format 0x2
08-13 12:19:07.866 D/ALSADevice(230): Device value returned is hw:0,0
08-13 12:19:07.866 D/ALSADevice(230): handle->format: 0x2
08-13 12:19:07.866 D/ALSADevice(230): setHardwareParams: reqBuffSize 2048 channels 2 sampleRate 48000
08-13 12:19:07.876 D/ALSADevice(230): setHardwareParams: buffer_size 16384, period_size 2048, period_cnt 8
08-13 12:19:09.518 I/auditd  (21266): Starting up
08-13 12:19:09.518 E/auditd  (21266): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:09.518 I/auditd  (21266): Exiting
08-13 12:19:11.079 D/ALSADevice(230): standby: handle 0xb587a680 h 0x0
08-13 12:19:11.260 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value Inactive
08-13 12:19:11.260 D/alsa_ucm(230): Set mixer controls for HiFi enable 0
08-13 12:19:11.260 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 0
08-13 12:19:11.260 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _disdev value Speaker
08-13 12:19:11.260 D/alsa_ucm(230): Set mixer controls for Speaker enable 0
08-13 12:19:11.260 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: ZERO
08-13 12:19:11.260 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: ZERO
08-13 12:19:11.270 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 0
08-13 12:19:11.270 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 0
08-13 12:19:11.270 D/alsa_ucm(230): Setting mixer control: RX5 Digital Volume, value: 0
08-13 12:19:11.270 D/AudioUsbALSA(230): exitPlaybackThread, mproxypfdPlayback: -1
08-13 12:19:11.270 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:19:11.270 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:19:12.211 V/WindowManager(679): Adding window Window{3b13ca0c u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 5 of 9 (after Window{3ebbc7dd u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
08-13 12:19:12.231 E/AudioTrack(679): AudioTrack::set : Exit
08-13 12:19:12.251 D/ALSADevice(230): route: devices 0x2 in mode 0
08-13 12:19:12.251 D/ALSADevice(230): No valid input device: 0
08-13 12:19:12.251 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _enadev value Speaker
08-13 12:19:12.251 D/ALSADevice(230): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Speaker
08-13 12:19:12.251 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value HiFi
08-13 12:19:12.251 D/alsa_ucm(230): Set mixer controls for Speaker enable 1
08-13 12:19:12.251 D/alsa_ucm(230): acdb_id 15 cap 1 enable 1
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_audio_cal, acdb_id = 15, path =  0
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_adm_topology
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_asm_topology
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_audtable
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_CAL
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_audvoltable
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
08-13 12:19:12.251 E/ACDB-LOADER(230): Error: ACDB AudProc vol returned = -8
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_afe_cal
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AFE_CAL
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> send_hw_delay : acdb_id = 15 path = 0
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_DEVICE_PROPERTY_SIZE
08-13 12:19:12.251 D/ACDB-LOADER(230): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
08-13 12:19:12.251 D/ACDB-LOADER(230): send_hw_delay id = 15 delay_num_entries = 1 result = 0
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: SLIM_0_RX Channels, value: Two
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: RX1
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: RX2
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: RX6 DSM MUX, value: DSM_INV
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 83
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 83
08-13 12:19:12.251 D/alsa_ucm(230): Setting multi value: RX5 Digital Volume
08-13 12:19:12.251 D/alsa_ucm(230): Set mixer controls for HiFi enable 1
08-13 12:19:12.251 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
08-13 12:19:12.251 D/ALSADevice(230): close: handle 0xb587a680 h 0x0
08-13 12:19:12.251 D/ALSADevice(230): open: handle 0xb587a680, format 0x2
08-13 12:19:12.251 D/ALSADevice(230): Device value returned is hw:0,0
08-13 12:19:12.261 D/ALSADevice(230): handle->format: 0x2
08-13 12:19:12.261 D/ALSADevice(230): setHardwareParams: reqBuffSize 2048 channels 2 sampleRate 48000
08-13 12:19:12.261 D/ALSADevice(230): setHardwareParams: buffer_size 16384, period_size 2048, period_cnt 8
08-13 12:19:13.772 W/InputMethodManagerService(679): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@1c3ed25b attribute=null, token = android.os.BinderProxy@1ba5fb4
08-13 12:19:13.802 E/AudioTrack(679): AudioTrack::set : Exit
08-13 12:19:14.543 I/auditd  (21281): Starting up
08-13 12:19:14.543 E/auditd  (21281): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:14.543 I/auditd  (21281): Exiting
08-13 12:19:16.985 D/ALSADevice(230): standby: handle 0xb587a680 h 0x0
08-13 12:19:17.165 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value Inactive
08-13 12:19:17.165 D/alsa_ucm(230): Set mixer controls for HiFi enable 0
08-13 12:19:17.165 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 0
08-13 12:19:17.165 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _disdev value Speaker
08-13 12:19:17.165 D/alsa_ucm(230): Set mixer controls for Speaker enable 0
08-13 12:19:17.165 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: ZERO
08-13 12:19:17.165 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: ZERO
08-13 12:19:17.175 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 0
08-13 12:19:17.175 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 0
08-13 12:19:17.175 D/alsa_ucm(230): Setting mixer control: RX5 Digital Volume, value: 0
08-13 12:19:17.175 D/AudioUsbALSA(230): exitPlaybackThread, mproxypfdPlayback: -1
08-13 12:19:17.175 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:19:17.175 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:19:19.568 I/auditd  (21290): Starting up
08-13 12:19:19.578 E/auditd  (21290): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:19.578 I/auditd  (21290): Exiting
08-13 12:19:24.593 I/auditd  (21302): Starting up
08-13 12:19:24.593 E/auditd  (21302): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:24.593 I/auditd  (21302): Exiting
08-13 12:19:29.628 I/auditd  (21313): Starting up
08-13 12:19:29.638 E/auditd  (21313): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:29.638 I/auditd  (21313): Exiting
08-13 12:19:34.662 I/auditd  (21321): Starting up
08-13 12:19:34.662 E/auditd  (21321): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:34.662 I/auditd  (21321): Exiting
08-13 12:19:39.707 I/auditd  (21332): Starting up
08-13 12:19:39.707 E/auditd  (21332): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:39.707 I/auditd  (21332): Exiting
08-13 12:19:44.732 I/auditd  (21342): Starting up
08-13 12:19:44.752 E/auditd  (21342): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:44.752 I/auditd  (21342): Exiting
08-13 12:19:49.787 I/auditd  (21350): Starting up
08-13 12:19:49.787 E/auditd  (21350): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:49.787 I/auditd  (21350): Exiting
08-13 12:19:54.812 I/auditd  (21360): Starting up
08-13 12:19:54.812 E/auditd  (21360): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:54.812 I/auditd  (21360): Exiting
08-13 12:19:59.827 I/auditd  (21370): Starting up
08-13 12:19:59.837 E/auditd  (21370): Failed on audit_set_pid with error: Protocol not supported
08-13 12:19:59.837 I/auditd  (21370): Exiting
08-13 12:20:04.872 I/auditd  (21380): Starting up
08-13 12:20:04.882 E/auditd  (21380): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:04.882 I/auditd  (21380): Exiting
08-13 12:20:09.887 I/auditd  (21388): Starting up
08-13 12:20:09.897 E/auditd  (21388): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:09.897 I/auditd  (21388): Exiting
08-13 12:20:14.922 I/auditd  (21399): Starting up
08-13 12:20:14.922 E/auditd  (21399): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:14.922 I/auditd  (21399): Exiting
08-13 12:20:19.947 I/auditd  (21409): Starting up
08-13 12:20:19.947 E/auditd  (21409): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:19.947 I/auditd  (21409): Exiting
08-13 12:20:24.972 I/auditd  (21417): Starting up
08-13 12:20:24.972 E/auditd  (21417): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:24.972 I/auditd  (21417): Exiting
08-13 12:20:29.986 I/auditd  (21427): Starting up
08-13 12:20:29.986 E/auditd  (21427): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:29.986 I/auditd  (21427): Exiting
08-13 12:20:32.109 V/WindowManager(679): Adding window Window{7c11bd1 u0 AtchDlg:com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 5 of 9 (after Window{3ebbc7dd u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
08-13 12:20:32.139 E/AudioTrack(679): AudioTrack::set : Exit
08-13 12:20:32.139 D/ALSADevice(230): route: devices 0x2 in mode 0
08-13 12:20:32.139 D/ALSADevice(230): No valid input device: 0
08-13 12:20:32.139 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _enadev value Speaker
08-13 12:20:32.139 D/ALSADevice(230): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Speaker
08-13 12:20:32.139 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value HiFi
08-13 12:20:32.139 D/alsa_ucm(230): Set mixer controls for Speaker enable 1
08-13 12:20:32.139 D/alsa_ucm(230): acdb_id 15 cap 1 enable 1
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_audio_cal, acdb_id = 15, path =  0
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_adm_topology
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_asm_topology
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_audtable
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_CAL
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_audvoltable
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
08-13 12:20:32.139 E/ACDB-LOADER(230): Error: ACDB AudProc vol returned = -8
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_afe_cal
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AFE_CAL
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> send_hw_delay : acdb_id = 15 path = 0
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_DEVICE_PROPERTY_SIZE
08-13 12:20:32.139 D/ACDB-LOADER(230): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
08-13 12:20:32.139 D/ACDB-LOADER(230): send_hw_delay id = 15 delay_num_entries = 1 result = 0
08-13 12:20:32.139 D/alsa_ucm(230): Setting mixer control: SLIM_0_RX Channels, value: Two
08-13 12:20:32.139 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: RX1
08-13 12:20:32.149 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: RX2
08-13 12:20:32.149 D/alsa_ucm(230): Setting mixer control: RX6 DSM MUX, value: DSM_INV
08-13 12:20:32.149 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 83
08-13 12:20:32.149 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 83
08-13 12:20:32.149 D/alsa_ucm(230): Setting multi value: RX5 Digital Volume
08-13 12:20:32.149 D/alsa_ucm(230): Set mixer controls for HiFi enable 1
08-13 12:20:32.149 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
08-13 12:20:32.149 D/ALSADevice(230): close: handle 0xb587a680 h 0x0
08-13 12:20:32.149 D/ALSADevice(230): open: handle 0xb587a680, format 0x2
08-13 12:20:32.149 D/ALSADevice(230): Device value returned is hw:0,0
08-13 12:20:32.159 D/ALSADevice(230): handle->format: 0x2
08-13 12:20:32.159 D/ALSADevice(230): setHardwareParams: reqBuffSize 2048 channels 2 sampleRate 48000
08-13 12:20:32.159 D/ALSADevice(230): setHardwareParams: buffer_size 16384, period_size 2048, period_cnt 8
08-13 12:20:35.021 I/auditd  (21439): Starting up
08-13 12:20:35.031 E/auditd  (21439): Failed on audit_set_pid with error: Protocol not supported
08-13 12:20:35.031 I/auditd  (21439): Exiting
08-13 12:20:35.352 D/ALSADevice(230): standby: handle 0xb587a680 h 0x0
08-13 12:20:35.532 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value Inactive
08-13 12:20:35.532 D/alsa_ucm(230): Set mixer controls for HiFi enable 0
08-13 12:20:35.532 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 0
08-13 12:20:35.532 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _disdev value Speaker
08-13 12:20:35.532 D/alsa_ucm(230): Set mixer controls for Speaker enable 0
08-13 12:20:35.532 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: ZERO
08-13 12:20:35.532 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: ZERO
08-13 12:20:35.542 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 0
08-13 12:20:35.542 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 0
08-13 12:20:35.542 D/alsa_ucm(230): Setting mixer control: RX5 Digital Volume, value: 0
08-13 12:20:35.542 D/AudioUsbALSA(230): exitPlaybackThread, mproxypfdPlayback: -1
08-13 12:20:35.542 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:20:35.542 D/AudioUsbALSA(230): closeDevice handle 0x0
08-13 12:20:36.743 V/WindowManager(679): not Base app: Adding window Window{8074ea4 u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 6 of 10
08-13 12:20:36.783 E/AudioTrack(679): AudioTrack::set : Exit
08-13 12:20:36.783 D/ALSADevice(230): route: devices 0x2 in mode 0
08-13 12:20:36.783 D/ALSADevice(230): No valid input device: 0
08-13 12:20:36.783 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _enadev value Speaker
08-13 12:20:36.783 D/ALSADevice(230): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Speaker
08-13 12:20:36.783 D/alsa_ucm(230): snd_use_case_set(): uc_mgr 0xb586f7c0 identifier _verb value HiFi
08-13 12:20:36.783 D/alsa_ucm(230): Set mixer controls for Speaker enable 1
08-13 12:20:36.783 D/alsa_ucm(230): acdb_id 15 cap 1 enable 1
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_audio_cal, acdb_id = 15, path =  0
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_adm_topology
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_asm_topology
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_audtable
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_CAL
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_audvoltable
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
08-13 12:20:36.783 E/ACDB-LOADER(230): Error: ACDB AudProc vol returned = -8
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_afe_cal
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> AUDIO_SET_AFE_CAL
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> send_hw_delay : acdb_id = 15 path = 0
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_CMD_GET_DEVICE_PROPERTY_SIZE
08-13 12:20:36.783 D/ACDB-LOADER(230): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
08-13 12:20:36.783 D/ACDB-LOADER(230): send_hw_delay id = 15 delay_num_entries = 1 result = 0
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: SLIM_0_RX Channels, value: Two
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP1, value: RX1
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: RX5 MIX1 INP2, value: RX2
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: RX6 DSM MUX, value: DSM_INV
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: LINEOUT2 Volume, value: 83
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: LINEOUT4 Volume, value: 83
08-13 12:20:36.793 D/alsa_ucm(230): Setting multi value: RX5 Digital Volume
08-13 12:20:36.793 D/alsa_ucm(230): Set mixer controls for HiFi enable 1
08-13 12:20:36.793 D/alsa_ucm(230): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
08-13 12:20:36.793 D/ALSADevice(230): close: handle 0xb587a680 h 0x0
08-13 12:20:36.793 D/ALSADevice(230): open: handle 0xb587a680, format 0x2
08-13 12:20:36.793 D/ALSADevice(230): Device value returned is hw:0,0
08-13 12:20:36.803 D/ALSADevice(230): handle->format: 0x2
08-13 12:20:36.803 D/ALSADevice(230): setHardwareParams: reqBuffSize 2048 channels 2 sampleRate 48000
08-13 12:20:36.803 D/ALSADevice(230): setHardwareParams: buffer_size 16384, period_size 2048, period_cnt 8
08-13 12:20:37.994 I/art     (679): Background sticky concurrent mark sweep GC freed 196282(9MB) AllocSpace objects, 15(355KB) LOS objects, 18% free, 34MB/42MB, paused 2.716ms total 245.391ms

**Comment by roryjw** [comment]
Extended logs at https://www.dropbox.com/s/9j9hsgfvgo1db7g/2015-08-13-14-59-39.txt?dl=0

**Comment by B--B** [comment]
How the auditd daemon is supposed to drain battery? http://linux.die.net/man/8/auditd
