### ISSUE TITLE
Lag while updating apps or when notifications appear

### ISSUE THREAD

**Issue by TessellatedGuy** [JDCTeam/issue_tracking_cm#38]
System UI stops or sometimes it becomes unresponsive when notifications arrive. Pls help! It's very unstable this way :.

**Comment by B--B** [comment]
Is it solved in latest build? Provide us more info and logs or close this bug. Thanks

**Comment by AntaresOne** [comment]
@TessellatedGuy we did not get an answer in 2 months, I'm closing this.
