### ISSUE TITLE
Bluetooth Share FC

### ISSUE THREAD

**Issue by angsanley** [JDCTeam/issue_tracking_cm#39]
When I tries to enable Bluetooth it just Force Closes. I'm on ext4 tho. GT-I9505 Singapore baseband.

**Comment by chengzhoukun** [comment]
Me  too.

**Comment by smeroni68** [comment]
For both:
wipe system, cache and dalvik. 
flash newly rom and gapps. 
re-wipe cache and dalvik. 
Reboot.

**Comment by kevingamble** [comment]
^^ did all of the above on initial install; still getting Bluetooth FCs.

SGH I337M.

**Comment by Bunjman** [comment]
Same here. Can't use Bluetooth. Locks up phone and then bootloops. I have factory reset and wioed all caches several times.
S4 SPH-L720

**Comment by AntaresOne** [comment]
^^ what baseband do you have?

**Comment by Bunjman** [comment]
L720VPUFNG2 

Sent by Outlook for Android

On Sun, Oct 4, 2015 at 10:09 AM -0700, "AntaresOne" notifications@github.com wrote:

^^ what baseband do you have?

**Comment by rosseloh** [comment]
AntaresOne, I've got the same issue - model SGH-I337Z (Cricket), baseband I337ZTUUBOA1. On initial boot, and subsequently whenever you or the system try to enable Bluetooth, the Bluetooth Share service crashes. It also takes your WiFi connection with it. WiFi comes back after a bit or if you disable/enable it.

Turning off Bluetooth and making sure I don't do anything to re-enable it keeps the system running smoothly (apart from a different issue that doesn't belong in this thread). I tried several fresh flashes when I first encountered the issue - the only thing I didn't do was change my partition formatting (I didn't see the option in TWRP).

Let me know if you need anything else.

**Comment by Draghtnod** [comment]
Souds like #14 and #35.
I got the same issue and wasn't able to use bluetooth since i'm using this rom.

```
Phone model: GT-I9505
Baseband version: I9505XXUHOF2
ROM version: 20150817
GApps Package: Open GApps Nano 20150823
Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no
```

**Comment by AntaresOne** [comment]
@everyone please update to the latest build available, and use an unique "bluetooth share" issue report.

https://github.com/JDCTeam/issue_tracking_cm/issues/35
