### ISSUE TITLE
Dialer Does not respond

### ISSUE THREAD

**Issue by barathn** [JDCTeam/issue_tracking_cm#4]
Hi,

It was working fine for couple of days, after which the dialer never responds. 

Tks
Barath

**Comment by jtash** [comment]
same issue (jfltespr)

**Comment by AntaresOne** [comment]
Please go in Settings->Apps->All->Dialer->Clear data

This must solve your issue. Wait for the new build, it's coming out soon

**Comment by AntaresOne** [comment]
@barathn @jtash no answers after 3 months, I'm closing this.
