### ISSUE TITLE
Mobile data not opening

### ISSUE THREAD

**Issue by sahaab** [JDCTeam/issue_tracking_cm#41]
Sgh-i337m
Network unlocked
My dad has exact same phone, but in stock rom and all is working fine.
I recently just came to Pakistan, got a sim from here and a data plan, but the data doesn't seem to be connecting on the phone for some reason. While my dad's phone on stock connects properly.
Pakistan normally has 3G, and my carrier is ufone. (Dad has same)
All works fine on my dad's stock rom, while mines doesn't connect to data, network and everything else working fine.
Using rom from this link with f2fs, http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/exclusive-antaresone-alucard24-s-t3066696

**Comment by B--B** [comment]
Please try to copy/paste APN settings from stock phone to your phone and then pick a log when your phone tries to connects to mobile data
