### ISSUE TITLE
Samsung S4 I9505 camera not working

### ISSUE THREAD

**Issue by ghost** [JDCTeam/issue_tracking_cm#42]
My Samsung S4 I9505 front facing camera is not working. And requires to reboot sometimes for the back camera to work. Please Fix. Thank you in advance

**Comment by maximiliengolum** [comment]
Mine is working, check your installation, or maybe update your camera firmware

**Comment by ghost** [comment]
Hmm I'm new to cyanogenmod. I do not know how to check installation and update camera firmware. Can help me out with this? Thanks!

**Comment by smeroni68** [comment]
Install an updated full stock TW lollipop rom with Odin... this will update all stuff of your phone including base firmwares...

**Comment by maximiliengolum** [comment]
One question,  wich camera app do you use ? I've notice that Google camera app don't work properly on my phone. Try with the stock one (if you haven't, reinstall with a gapps who don't replace your camera app)

**Comment by ceribik** [comment]
> Install an updated full stock TW lollipop rom with Odin... this will update all stuff of your phone including base firmwares...

Is this a requirement for proper camera support in your ROM? My i9505 currently has a pre-KNOX baseband.

**Comment by ghost** [comment]
Yeap I just revert back to stock rom and its the lastest rom. The camera is working but when i install CM again, the front camera cannot connect.

**Comment by maximiliengolum** [comment]
What is your camera app ? If it's the Google one installed by open gapps, try to install a pico gapps, without Google camera, ans test with the stock app
(For me the Google camera app installed from the playstore doesn't work)

**Comment by seapython** [comment]
Please note that the S4 camera firmware is upgraded when installing stock 5.0.1, but this only happens when the camera is first used after the ROM upload.
So the pathway to a CM ROM should be: Upload stock Samsung 5.0.1 -> start the camera -> allow camera firmware upgrade to finish -> shut down -> root etc and upload the CM ROM.
I have had no camera issues with either of the last two builds.

**Comment by B--B** [comment]
Camera works, it's a firmware-related issue in users phones, not rom-related. This is a bug tracker and there's an xda thread for that kind of discussions.
