### ISSUE TITLE
Character Recognition

### ISSUE THREAD

**Issue by jluisfgarza** [JDCTeam/issue_tracking_cm#45]
Character Recognition: The system displays a square, instead of accents and other characters. (á é í ó ú ñ, etc.)

**Comment by B--B** [comment]
Provide more info as requested and your language, everything works fine on italian language

**Comment by ghost** [comment]
Samsung i337m, spanish. The problem is not always, but on certain apps.

**Comment by AntaresOne** [comment]
@JuanLuisFG it depends exclusively on the apps, report closed as not ROM's bug.
