### ISSUE TITLE
Samsung Galaxy S4 starts booting when switched off and plugged to power cable

### ISSUE THREAD

**Issue by ginoginelli** [JDCTeam/issue_tracking_cm#46]
Having updated my Samsung Galaxy S4 GT-I9505 from Android 4.3 stock ROM (but rooted) to
Cyanogen Mod 12.1 (http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/exclusive-antaresone-alucard24-s-t3066696), I found that the mobile phone is booting if I connect it to a
power cable while its switched off.
To be more precise, I did the following, coming from Android 4.3:
(1) Create a full NAndroid backup of the Android 4.3 sytem (including apps, EFS, etc.) using TWRP 2.6.3.1.
(2) Upgrade from TWRP 2.6.3.1 to TWRP 2.8.7.0 as suggested.
(3) Download the Custom ROM and the GApps package; I used the ARM/5.1/nano variant.
(4) Put the zip files on my SD card, reboot in recovery, wipe data / factory reset. 
(5) Select "Install", choosing the ROMs Zip file first and then the GApps Zip file. I did not convert to f2fs.
     I left the ext4 file system on all my partitions.
(6) Reboot the system after the installation was finished.
(7) Wait until the reboot is fully finished. Shut down the system afterwards without doing any other
     steps.
(8) 5 minutes after shutdown: Connect the mobile phone to power cable for charging.

After a few minutes, I noticed that the phone was booting, and I had to enter the PIN of my SIM card.
I tried this with several different cables, power connectors and accumulators - the result was always
the same.
However, it only happens with the Custom ROM. I created a full backup again, finding the following:
Restore the Android 4.3 backup ==> the issue does not occur. Mobile phone is charging, but remains switched off.
Restore the Custom ROM backup ==> the issue occurs.
I'm afraid that I can't provide any log files, because the issue happens when the phone is switched off.

Please find below my device details:
build.board: MSM8960
build.bootloader: I9505XXUEMKE
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: jfltexx
build.display: LMY48G
build.fingerprint: samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys
build.hardware: qcom
build.host: JDCTeam
build.id: LMY48G
build.manufacturer: samsung
build.model: GT-I9505
build.product: jflte
build.radio: unknown
build.serial: 4612052d
build.tags: test-keys
build.time: 1439821114000
build.type: userdebug
build.user: b--b
version.codename: REL
version.incremental: 9c1298432f
version.release: 5.1.1
version.sdk_int: 22

**Comment by AntaresOne** [comment]
@ginoginelli no such issue here. You should update your bootloader, and do not forget baseband too. Report closed
