### ISSUE TITLE
no td-scdma support on i9508

### ISSUE THREAD

**Issue by xray447** [JDCTeam/issue_tracking_cm#48]
clean install on 20150817,base band is I9508zmujoa1,no way to active td-scdma mode,it always change to wcdma

**Comment by AntaresOne** [comment]
@xray447 we need a radio logcat, also provide other informations as for the README. Please install the most recent ROM build and use syslog app to get a logcat rightly after you try to choose TD-SCDMA. Closing this for now, reopen if you need.
