### ISSUE TITLE
"Failed to install theme" comes up on most themes

### ISSUE THREAD

**Issue by BigVner** [JDCTeam/issue_tracking_cm#49]
After Gplay finished downloading and installing, that error above comes up with most themes, either when I try it from Gplay or per apk...
(i9505; everything on newest version)

 ♦  I tested "Dark Material" 
    > https://play.google.com/store/apps/details?id=com.chummy.jezebel.material.dark 
 ♦  and "Deep Darkness"
    > https://play.google.com/store/apps/details?id=com.blissroms.moelle.deepdarknesscm12

(And some other themes, but I won't list all of course)

**Comment by BigVner** [comment]
Here is a catlog, from when I try downloading the Dark Material theme:
https://drive.google.com/file/d/0B-CSSleUMMcQMkpuejRVNkh5SE0/view?usp=sharing

I hope sombody can help

**Comment by benjamen50** [comment]
Solution is here, I think it's a GApps issue or some kind of conflict between the Deskclock App(s)

![7t41ckt](https://cloud.githubusercontent.com/assets/11651816/9574403/ef7fa898-5009-11e5-82eb-51baa30c377b.png)

**Comment by BigVner** [comment]
Ok thanks, the stock deskclock app wasn't working anyway... It instantly crashed when I tried to open it.

**Comment by AntaresOne** [comment]
@BigVner do you have Facebook Messenger installed? Closing this for now, reopen if you need.
