### ISSUE TITLE
Sound issues.

### ISSUE THREAD

**Issue by alfredo9908** [JDCTeam/issue_tracking_cm#50]
CyanogenMod version: OptimizedCM-12.1-20150817
Android version: 5.1.1
System modifications: NO
Xposed Framework: Absolutely not.
Did I flash another Kernel: Nope.
Phone model: Galaxy S4 (SGH-I337M)

Please help me with some sound issues I've been experiencing:
1) In WhatsApp, when I send a voice note, I can't hear it, when I play it, it is very low volume, and when someone send me voice notes, at the very last second, it stops, and I can't hear what they say in the end.
2) When I'm playing sound (Videos on Facebook for example) and connect the headphones, the sound also playa in the little speaker (the one where you hear a call) and I don't know why.

I'm a little worried about this because I've been looking for a solution and found nothing, also I did all the steps good when I flashed this ROM, I own a Galaxy S4 (SGH-I337M)
PLZ HELP ME!!!

**Comment by AntaresOne** [comment]
@alfredo9908 please update to the latest ROM build first.

1) Boost microphone gain in STweaks (do not exceed 50)
2) No such issue here, maybe that was an old Facebook versio issue.
