### ISSUE TITLE
Media Crashes when receiving messages

### ISSUE THREAD

**Issue by Shashaank5** [JDCTeam/issue_tracking_cm#52]
When I get a message from facebook sometimes my media crashes for example if I'm listening to the song it will stutter and then go to the next song l.  On YouTube it will just say network error has occurred

**Comment by ImNotJayy** [comment]
Sale for me, the song stutter and then it stops, i have to turn off and on the bluetooth everytime this happens :/

**Comment by Shashaank5** [comment]
Sometimes system ui crashes as well when this happens

**Comment by AntaresOne** [comment]
@InTerKineTic @ImNotJayy no other informations provided as the README says, and no logs. Report closed, please reopen it if you need and provide asked stuff
