### ISSUE TITLE
Mobile Data

### ISSUE THREAD

**Issue by kevinhinterlong** [JDCTeam/issue_tracking_cm#53]
Phone model: jfltespr (GT-I9505)
Baseband version: L720VPUAMDC (I realize this is extremely old, but I had various issues with flashing modem upgrades on custom ROMs)
ROM version: 20150817
GApps Package: (I most likely installed OpenGapps nano 4-21-2015)

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? No
Did you flash another kernel? no
Did you install Xposed framework? no

I know there are often problems with using mobile data with the Sprint network on a custom rom, at least in my past experiences using my GS4; however, after the last update which fixed stagefright and other things I seep to have lots of problems accessing/editing the APN settings and my phone will often need to be restarted.

**Comment by ravv7** [comment]
Yes I have this problem too on Vodafone CZ carrier. Data stop working and need reboot. I have written it before. Now I have instaled nightlie ROM and data working ok. But USB connection to PC don't work, which works fine on Optimised ROM.

**Comment by zfilinger** [comment]
I have a similar issue - mobile data not working on Vodafone CZ carrier. It used to work at some places in the city, but now it almost doesn't work at all. Sometimes I see the exclamation mark in the signal icon, sometimes I see the H, but when I try to access any website, I get an error message that there's no internet connection.

Is there something I can try to resolve the issue? I'd be happy to provide or test anything that might lead to resolving this issue.

Phone model: GT-I9505
Baseband version: I9505XXUGNG8
ROM version: 20150725
GApps Package: Slim GApps 5.1 20150501

Did you do a clean install for the currently installed build? yes 

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

**Comment by AntaresOne** [comment]
@everyone please update to the latest ROM version available, I'm closing this report, reopen it if you need.
