### ISSUE TITLE
Lag and battery drain

### ISSUE THREAD

**Issue by galaxyx7** [JDCTeam/issue_tracking_cm#54]
Hi guys!

First of all thank you so much for creating such an awesome OS. I know that you have a lot of work, but I have to tell you about a couple of issues:
- when I connect to WiFi/cellular the phone lags for about 30 seconds; it usually happens when I turn on internet after a couple of hours and I suddenly get a lot of new stuff (FB, Instagram, Snapchat ect.)
- phone lags bad at random times when I wake it up - it takes 60s+ to start any app

on both occasions I have to wait 20s+ for the power menu to open - I simply have to reboot the phone in order to get it working again!

Also the battery drains like crazy when I use the phone for 10 minutes or more, especially when I connect to the Internet.
- Charging the battery also takes FOREVER (5hrs+ for a 100% charge)! 

I did a fresh install yesterday: full wipe with kernel cleaner (http://forum.xda-developers.com/nexus-4/development/mod-kernel-cleaner-script-superwipe-t2121701). Installed the ROM, Open Gapps stock and then continued to install my apps (about 35).

Otherwise I'm not experiencing any other issues. Bluetooth works flawlessly! :)

My logcat:
http://pastebin.com/SnLXbqgn

![screenshot_2015-09-14-23-53-09](https://cloud.githubusercontent.com/assets/10668176/9863008/d888839c-5b3c-11e5-8611-df5eaec18830.png)
![screenshot_2015-09-14-23-53-55](https://cloud.githubusercontent.com/assets/10668176/9863009/d88d23de-5b3c-11e5-97a9-ff8ceb328538.png)

EDIT:

I've also used these mods: [url]http://forum.xda-developers.com/showpost.php?p=62515538&postcount=5683[/url]

And now I've tried to disable Google services stuff via Privacy guard ([url]http://forum.xda-developers.com/showpost.php?p=62513818&postcount=5675[/url])

**Comment by AntaresOne** [comment]
Hello,
Please revert to stock STweaks settings and try for at least two days if your issues are gone.
To revert swipe all the right until "PROFILES" and then press "DEFAULT". If you still have the same issues try once again a clean install with OpenGapps micro or less package, either check what apps you installed (remember that instant messaging, Facebook and things like will increase battery drain A LOT, and do not forget that you should not use any RAM tweaker, cleaner etc.). Also check if GPS is always-on and for wakelocks with BetterBatteryStats. What SOT time from that image?

For the battery either try to force fast charging in STweaks (AC/USB CHARGING CONTROL tab). If after everything you still experience the same issues consider a faulty hardware or battery.

Do not forget to update this issue report and please fill out [this form](https://github.com/JDCTeam/issue_tracking_cm/blob/master/README.md).

Thank you,
AntaresOne

**Comment by AntaresOne** [comment]
@galaxyx7 no answer after a month, report closed.
