### ISSUE TITLE
Cellular disconnect

### ISSUE THREAD

**Issue by tranvuvuong** [JDCTeam/issue_tracking_cm#55]
I get frequently disconnect from cellular signal. I can receive SMS, but cannot send, make calls etc. Just did a clean flash today

**Comment by AntaresOne** [comment]
Hi,
We ask to do each issue report with [this](https://github.com/JDCTeam/issue_tracking_cm/blob/master/README.md), also you didn't specify your device variant, carrier and baseband firmware.
Once you're ready you can reopen this bug report
