### ISSUE TITLE
Issue HDR photos

### ISSUE THREAD

**Issue by CiccioP95** [JDCTeam/issue_tracking_cm#56]
Using the Google Camera App, I can't take any photo with the HDR effect, because appears a window to report or ignore the error. Besides, sometimes I have any problems with the frontal camera: while I take a photo, it blocks definitevely and I must restart the OS to open again the app.
Phone model: GT-I9505
Baseband version: I9505XXUFNB8
ROM version:  20150817
GApps Package: Open GApps Nano 20150726
Did you do a clean install for the currently installed build? YES
Did you reboot after having the issue? Yes
Did you do any system modification? NO
Did you flash another kernel? NO
Did you install Xposed framework? NO

**Comment by AntaresOne** [comment]
Hi,
HDR is not compatible with CM-based ROMs, therefore its crash is a normal behavior. About the front camera we're already investigating since many time and will require more time.
Thank you,
AntaresOne
