### ISSUE TITLE
Sound lags

### ISSUE THREAD

**Issue by lonkodonko** [JDCTeam/issue_tracking_cm#58]
Phone model: GT-I9505
Baseband version: I9505XXUHOH2
ROM version: 20150817

GApps Package: Open GApps [arm 5.1 aroma] [20150726]

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

When i play music in any app I have some sound lags. 
The sound freezes for 250 - 500ms and sounds like an typical error sound. For example a quiz show fail sound. ^^

**Comment by revnu** [comment]
I can confirm this soundbug. Itz kinda general bug, but it only shows in some apps.

If you want to test it just set an alarm, and listen to the "beep" it hangs some times.

Or a better way to test is: install the app "prostate aerobics" [of course dont ask me why I need this app ;) ]. In this app you can clearly reproduce the error. If you start a training-lesson the voice will start and say "contract". But after that sound will bug completly and will be gone. Test it with other ROMs, and it will be fine.

Hope this will be fixed

**Comment by revnu** [comment]
Can some developer please respont to this issue and tell us if this problem is already regognized and worked on??

This bug also makes that audiomessages in whatsapp are interrupted at the end

**Comment by revnu** [comment]
Here is a workaround I get from one developer, I bet they have many work to do with all the bugs, so I help here ist the solution, untill it is fixed:

We're currently aware of this issue as steadily said here, and asked to the kernel developer to look into it but I still don't have any news back from him

Quote:
Originally Posted by rothmark

There is something wrong with auditd in this ROM, it restarts every 2/3 seconds:
auditd (29957): Failed on audit_set_pid with error: Protocol not supported
Recompiling with "ARCH_ARM_HAVE_TLS_REGISTER := true" does not change that.
Just removed auditd from /system/bin.

Auditd is not restarting every some seconds but always alive and just spamming the log, I'm building the kernel without audit=1 as I don't need it. Just ignore, it's harmless

**Comment by revnu** [comment]
hm, ok didnt solve it for me......maybe I misunderstood that
