### ISSUE TITLE
Pink Screen/Crashes and Lost saved wifi networks

### ISSUE THREAD

**Issue by K1ck09** [JDCTeam/issue_tracking_cm#59]
Hello,

I installed this ROM and I have some issues:

1° Random Pink Screens and Crashes.
2° If the phone crashes i lost all of saves wifi network.

Best regardars,

**Comment by smeroni68** [comment]
Are you able to provide logs?

**Comment by K1ck09** [comment]
I don't know how I can get the logs... How I get the logs?
