### ISSUE TITLE
Speaker/headphones bug 

### ISSUE THREAD

**Issue by aang56** [JDCTeam/issue_tracking_cm#63]
After I listened to a voice message in whatsapp (only if I listened it via speaker. Not the speaker on the back of the phone, but the speaker which you use for calls. Its over the samsung sign), my sound bugs. When I listen To music via headphones the sound comes out of the headphones and the speaker. But it only should come out of the headphones. Sorry for my Bad english. Hope u'll understand it

**Comment by aang56** [comment]
Phone model: GT-I9505
Baseband version: I9505XXUHOB7
ROM version: 20151022

GApps Package: opengapps micro 5.1 ARM

Did you do a clean install for the currently installed build? yes 
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework?no

**Comment by anonymixer** [comment]
I have a similar problem ... but mine is that when you get an audio listening via whatsapp goes well but when finish the audio or voice memo hear from cut .... and also listening to music out all cut and if it were to be defective music .... any solution

**Comment by aang56** [comment]
Yeah i got this too. I had to tell my friends To Stop sending me voice messages
