### ISSUE TITLE
Bricked s4 2 days after latest update

### ISSUE THREAD

**Issue by joaobastosvet** [JDCTeam/issue_tracking_cm#64]
Hi, probably I made some mistake since i´m new to this things. It´s about (or not...) the latest JDCteam update sent to my s4 i9505  I have flashed it and Gaps also. All fine for 2 days, after that it just bricked during standby. My s4 i9505 sometimes root to cwm 6.0.4.7 (but not for long) has the phone keeps shuting down and rebooting in an endless cycle. Download mode still works. I could make wipe data and factory reset but when I root Rom it tells me that it can´t copy E:metadata/google.... (something like that...) and it aborts instalation. Is there any thread that could help me unbricking my phone? Thanks

**Comment by AntaresOne** [comment]
Hi, you must upgrade your recovery as CWM is ancient and no longer supported. Look for TWRP recovery, install it and then reflash the ROM
