### ISSUE TITLE
Freezing a boot screen

### ISSUE THREAD

**Issue by roscocheeta** [JDCTeam/issue_tracking_cm#65]
Did a fresh install wipe using TWRp, then installed the latest release (20151022) and cleared caches. Upon first boot up at the custom boot animation (DevCOnnection) it froze. Restarted again, and it loaded, bu wireless didn't work. 

So I did a fresh install wip again using TWRP and installed the versoin PRIOR to 20151022. This booted up fine, no problems. Went through setup, re-added SuperSU via TWRP. 

Then via OTA installed the latest 20151022 update. After it booted up, again froze on the DevConnection boot screen. I then pulled battery, booted it up again, this time it got through.

Later on via TWRP i installed SuperSU, booted up after that, again froze on the DevConnection boot up logo. Did one more hard battery pull, and it has been okay since. 

Thought it was worth raising as it did NOT happen with the release prior to 20151022

**Comment by guyhindle** [comment]
Similar issues.

Froze ONCE during bootup (but on a couple of separate occasions) whilst upgrading.  No problems since
