### ISSUE TITLE
Bluetooth keeps crashing

### ISSUE THREAD

**Issue by envis-nl** [JDCTeam/issue_tracking_cm#66]
Installed
- OptimizedCM-12.1-20151022-jflte.zip
- open_gapps-arm-5.1-stock-20151023.zip

Completely cleaned phone, installed CM12.1 and afterwards the open GApps. Everything is working except bluetooth.

Before this update I installed a new modem version on my phone I9505XXUHOF2. Can this be the problem? Should I revert to the old modem? No clue which one to use.

Any input appreciated :)

**Comment by gradebg96** [comment]
I had this problem the first time I dirty flashed.  I dirty flashed a second time, cleaned cache and dalvik then it was fine.  Another guy on page 712 of the thread suggested this and it worked for me

**Comment by guyhindle** [comment]
I've got the BT stack failing after a period of time - don't know how to take logs for you, any tips?

**Comment by thomas41587** [comment]
Same issue here
OptimizedCM-12.1-20151101-jflte.zip
open_gapps-arm-5.1-mini-20151108.zip

I did a clean install (wiped everything except external SD card)
I have modem version I9505XXUHOB8

How can I create a logfile in order to provide the DEVs with information?

**Comment by gllmhyt** [comment]
Not working too.
- ROM: 20151101
- OpenGapps: 20151115
- MDM: XXUHOH2

**Comment by thomas41587** [comment]
My issue regarding bluetooth is now solved.
I wiped everything except user data and then installed 20151101 and gapps again.
Maybe there was something wrong during the installation when I did the same things last time...

**Comment by Draghtnod** [comment]
Same issue here with a clean install of 20151130. Strangely, i never had this issue with 20151101. After I reverted to 20151101, Bluetooth works fine again.

**Comment by pidg30n** [comment]
I'm having this issue as well...  Installed the latest 1-18-16 release,  followed F2FS instructions...  Will try reading flashing soon.

**Comment by iGneousRock** [comment]
Yup, my bluetooth just pairs with devices randomly. Very inconsistent
