### ISSUE TITLE
Unfortunately, Clock has stopped - with log

### ISSUE THREAD

**Issue by gradebg96** [JDCTeam/issue_tracking_cm#67]
For the past two ROMs, everytime I go to clock it crashes.  Device info and log below, apologies it would not let me attach directly.

build.board: MSM8960
build.bootloader: I9505XXUDMH6
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: jfltexx
build.display: LMY48W
build.fingerprint: samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys
build.hardware: qcom
build.host: Asus-N551JX
build.id: LMY48W
build.manufacturer: samsung
build.model: GT-I9505
build.product: jflte
build.radio: unknown
build.serial: 447c656a
build.tags: test-keys
build.time: 1446252652000
build.type: userdebug
build.user: antaresone
version.codename: REL
version.incremental: 37d3155df0
version.release: 5.1.1
version.sdk_int: 22

11-01 13:23:43.398 I/auditd  (23195): Starting up
11-01 13:23:43.408 E/auditd  (23195): Failed on audit_set_pid with error: Protocol not supported
11-01 13:23:43.408 I/auditd  (23195): Exiting
11-01 13:23:48.433 I/auditd  (23207): Starting up
11-01 13:23:48.453 E/auditd  (23207): Failed on audit_set_pid with error: Protocol not supported
11-01 13:23:48.453 I/auditd  (23207): Exiting
11-01 13:23:48.543 D/PhoneStatusBar(2408): disable: < expand ICONS\* alerts SYSTEM_INFO\* back home recent clock search >
11-01 13:23:48.583 V/PhoneStatusBar(2408): setLightsOn(true)
11-01 13:23:49.404 I/ActivityManager(774): START u0 {act=android.intent.action.SHOW_ALARMS flg=0x14000000 cmp=com.android.deskclock/.HandleApiCalls} from uid 10010 on display 0
11-01 13:23:49.454 V/WindowManager(774): addAppToken: AppWindowToken{7db8025 token=Token{15702c1c ActivityRecord{1272c18f u0 com.android.deskclock/.HandleApiCalls t19}}} to stack=1 task=19 at 0
11-01 13:23:49.484 V/PhoneStatusBar(2408): setLightsOn(true)
11-01 13:23:49.554 I/ActivityManager(774): Start proc 23216:com.android.deskclock/u0a60 for activity com.android.deskclock/.HandleApiCalls
11-01 13:23:49.674 I/GAv4    (23216): Google Analytics 7.8.95 is starting up. To enable debug logging on a device run:
11-01 13:23:49.674 I/GAv4    (23216):   adb shell setprop log.tag.GAv4 DEBUG
11-01 13:23:49.674 I/GAv4    (23216):   adb logcat -s GAv4
11-01 13:23:49.684 W/GAv4    (23216): AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
11-01 13:23:49.684 W/ActivityManager(774): getRunningAppProcesses: caller 10060 does not hold REAL_GET_TASKS; limiting output
11-01 13:23:49.694 W/GAv4    (23216): CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
11-01 13:23:49.724 I/Timeline(23216): Timeline: Activity_launch_request id:com.android.deskclock time:1192115
11-01 13:23:49.724 I/ActivityManager(774): START u0 {cmp=com.android.deskclock/.DeskClock (has extras)} from uid 10060 on display 0
11-01 13:23:49.724 W/GAv4    (23216): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
11-01 13:23:49.734 V/WindowManager(774): addAppToken: AppWindowToken{1df75387 token=Token{374787c6 ActivityRecord{2768f9a1 u0 com.android.deskclock/.DeskClock t20}}} to stack=1 task=20 at 0
11-01 13:23:49.734 D/AlarmClock/Events(23216): [Alarm] [Show] [Intent]
11-01 13:23:49.734 I/AlarmClock(23216): HandleApiCalls show alarms
11-01 13:23:49.734 V/WindowManager(774): Based on layer: Adding window Window{c89c99e u0 Starting com.android.deskclock} at 8 of 11
11-01 13:23:49.834 D/PhoneStatusBar(2408): disable: < expand icons\* alerts system_info\* back home recent clock search >
11-01 13:23:49.945 D/AndroidRuntime(23216): Shutting down VM
11-01 13:23:49.945 E/AndroidRuntime(23216): FATAL EXCEPTION: main
11-01 13:23:49.945 E/AndroidRuntime(23216): Process: com.android.deskclock, PID: 23216
11-01 13:23:49.945 E/AndroidRuntime(23216): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.deskclock/com.android.deskclock.DeskClock}: android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 8
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread.access$900(ActivityThread.java:154)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.os.Looper.loop(Looper.java:135)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread.main(ActivityThread.java:5294)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at java.lang.reflect.Method.invoke(Native Method)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at java.lang.reflect.Method.invoke(Method.java:372)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
11-01 13:23:49.945 E/AndroidRuntime(23216): Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 8
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.deskclock.provider.ClockProvider.query(Unknown Source)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.content.ContentProvider.query(ContentProvider.java:1000)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.content.ContentResolver.query(ContentResolver.java:478)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.content.ContentResolver.query(ContentResolver.java:422)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.deskclock.provider.b.b(Unknown Source)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.deskclock.alarms.AlarmStateManager.I(Unknown Source)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.deskclock.alarms.AlarmStateManager.H(Unknown Source)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at com.android.deskclock.DeskClock.onCreate(Unknown Source)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.Activity.performCreate(Activity.java:5990)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
11-01 13:23:49.945 E/AndroidRuntime(23216):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
11-01 13:23:49.945 E/AndroidRuntime(23216):     ... 10 more
11-01 13:23:49.945 W/ActivityManager(774):   Force finishing activity 1 com.android.deskclock/.DeskClock
11-01 13:23:49.995 I/OpenGLRenderer(774): Initialized EGL, version 1.4
11-01 13:23:50.465 W/ActivityManager(774): Activity pause timeout for ActivityRecord{2768f9a1 u0 com.android.deskclock/.DeskClock t20 f}
11-01 13:23:50.695 I/Timeline(22739): Timeline: Activity_idle id: android.os.BinderProxy@25b1418d time:1193087
11-01 13:23:50.936 D/HeadsetStateMachine(10717): Disconnected process message: 10, size: 0
11-01 13:23:50.936 W/ctxmgr  (4040): [PowerConnectionState]Got same value as before for power connection (Plug state: 3 BatteryLevel: 1.0)
11-01 13:23:51.266 I/Timeline(774): Timeline: Activity_windows_visible id: ActivityRecord{23e2f267 u0 com.nolanlawson.logcat/.LogcatActivity t13} time:1193653
11-01 13:23:52.157 I/Process (23216): Sending signal. PID: 23216 SIG: 9
11-01 13:23:52.177 W/InputMethodManagerService(774): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@f4769b2 attribute=null, token = android.os.BinderProxy@11eb72e5
11-01 13:23:52.177 V/PhoneStatusBar(2408): setLightsOn(true)
11-01 13:23:52.257 I/ActivityManager(774): Process com.android.deskclock (pid 23216) has died

**Comment by AntaresOne** [comment]
Hi,
Please clean app's data in Settings->Apps->All, I had the same once and fixed in this way

**Comment by gradebg96** [comment]
Perfect, thank you very much!
