### ISSUE TITLE
Can't have /system on f2fs

### ISSUE THREAD

**Issue by ralfbergs** [JDCTeam/issue_tracking_cm#7]
Installed TWRP 2.8.7.0-AntaresOne. Converted `/cache`, `/data`, and `/system` to F2F2. Installed `cm-12.1-20150709-NIGHTLY-jfltexx`.

Noticed that at first the install process said `detected filesystem f2f2 for .../by-name/system`. Then it said `Patching system image unconditionally...`, then it said `detected filesystem ext4 for .../by-name/system`.

I'm pretty sure I followed all instructions exactly to the word.

**Comment by MatthewBooth** [comment]
Official CyanogenMod doesn't support F2FS to my knowledge.

This is the issue tracking for the  non-official "Optimised"  builds by
the  Jflte Dev Connection team... Which does support F2FS!

:)

**Comment by ralfbergs** [comment]
Ooops, I was not aware of this. Sorry, but I just started today with this... :-)
Thanks for your quick response!

**Comment by MatthewBooth** [comment]
That's no problem  :)  Everyone is new once!

Here's the JDC builds that this tracker is for,  we support F2FS.

http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/exclusive-antaresone-alucard24-s-t3066696
