### ISSUE TITLE
Android Keyboard Swipe not working anymore

### ISSUE THREAD

**Issue by Draghtnod** [JDCTeam/issue_tracking_cm#71]
Phone model: GT-I9505
Baseband version: I9505XXUHOF2
ROM version: 20151101

GApps Package: Open GApps [arm 5.1 nano] [20151108]

Did you do a clean install for the currently installed build? no
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

Just upgraded from 20151022 to 20151101. Everything is fine (even Bluetooth), but the Keyboard just won't swipe. I tried cleaning Cache/Dalvik, deleting Keyboard Data and Cache, restarting Keyboard, turning Swipe off and on, restarting phone. But it just stays off. :(

**Comment by gllmhyt** [comment]
Same:

Phone model: GT-I9505
Baseband version: I9505XXUHOH2
ROM version: 20151101

GApps Package: Open GApps [arm 5.1 nano] [20151115]

Did you do a clean install for the currently installed build? No, I don't want to delete and recreate my configuration every once in a while.
Did you reboot after having the issue? Yes, and cleaned the caches.
Did you do any system modification? Yes, adding CACert's root certificates.
Did you flash another kernel? No.
Did you install Xposed framework? Yes, and uninstalled it to see if it's working: no.

**Comment by Draghtnod** [comment]
I installed Googles version of the keyboard from the PlayStore. Swipe works with it again.

**Comment by gllmhyt** [comment]
I'd prefer not to install a supplementary package just because the default one is not working.
