### ISSUE TITLE
You cannot cancel two notifaction at a time

### ISSUE THREAD

**Issue by yannick9906** [JDCTeam/issue_tracking_cm#72]
Phone model: GT-I9505
Baseband version: ex. I9505XXUHOD7
ROM version: 20151101
GApps Packag: Stock Arm 5.1 20150821

Did you do a clean install for the currently installed build? no

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

I already reported this "bug" to AOSP but they said I should report it here.

If you cancel a notifaction via swipe, you cannot use two or more fingers two cancel two or more notifactions at a time. Same for Multitaskingview.

**Comment by AntaresOne** [comment]
Hi, I never heard of multitouch to delete notifications. If you have a reliable video which shows this feature (no manufacturer ROMs!), and for sure is not part of AOSP and derivated custom ROMs, link it here.
