### ISSUE TITLE
Any chance to add "BSOD killer" feature like optimized CM?

### ISSUE THREAD

**Issue by xray447** [JDCTeam/issue_tracking_cm#73]
cm-13.0-20151108-UNOFFICIAL-jflte 
I know Antaresone wont support cm13 anymore, but it's still crash after screen off.
I would appreciate that if you add "bsod killer"feature

**Comment by xray447** [comment]
Device:9508
Baseband:I9508ZMUJOA1

**Comment by AntaresOne** [comment]
Hello,
that ROM will not be developed, therefore I'll not add that, sorry.
Have a nice day!
