### ISSUE TITLE
Call hanging up not working

### ISSUE THREAD

**Issue by rigo9** [JDCTeam/issue_tracking_cm#78]
Cant receive incoming calls and on outgoing calls cant hang up. After pressing the call hang up button it says hanging but nothing happens.

**Comment by RichardoC** [comment]
I also have this issues. Also if I press the dialpad during the call nothing is sent. Audio from calls also can only be heard from the front speaker, selecting the back speaker of Bluetooth doesn't work.
Using I9505 on O2/giffgaff

Further Details

Phone model:  GT-I9505
Baseband version: ex. I9505XXUEMK8
ROM version: ex. OptimizedCM-13-20160509
GApps Package:  Open GApps full 20160511

Did you do a clean install for the currently installed build? yes 

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

**Comment by RichardoC** [comment]
Seems to have been fixed by flashing XXUHOL4 modem and bootloader from 
http://forum.xda-developers.com/galaxy-s4/general/ref-galaxy-s4-i9505-modems-bootloaders-t3315987
