### ISSUE TITLE
Logcat not working anymore

### ISSUE THREAD

**Issue by 0xTom** [JDCTeam/issue_tracking_cm#79]
Phone Model: GT-I9505
Basemand: I9505XXUHOH2
ROM-Version: 20151130
GApps: Slim_zero_gapps.BETA.5.1.build.0.x-20151203
Clean install: yes

Hi,
iam devoloping Apps for Android and from now with newest version of this ROM, logcat doesnt work any more (logcat windows in Android Studio is empty). Ive tried to use logat from CMD with "adb logcat" but then the error "unable to open log device 'main' " show up. Ive tried to open the hidden service menu with _#_#2846579#_#_ but the menu doesnt show up. Then Ive tried to activate logcat with "adb shell -> logcat enable" but this command isnt known by my Android System.

**Comment by dj-plx** [comment]
My Specs are identical to 0xTom except GApps (I use OpenGapps Aroma).
Kernel-Version: 3.4.110 (2015-11-30)

same issue here. logcat in adb shell returns:
 Unable to open log device 'main'

**Comment by B--B** [comment]
https://github.com/AOSP-JF/platform_device_samsung_jflte/commit/761585eda6c01a02c1d2619c012a16eb7419ec17
This should fix the issue, tested on our lp, logcat is working again

EDIT: not a good solution, kickstart keep crashing every few seconds, must be fixed on kernel side
