### ISSUE TITLE
no simcard samsung s4 (KPN simcard with nfc)

### ISSUE THREAD

**Issue by jeemy1122** [JDCTeam/issue_tracking_cm#82]
I received an new simcard from my provider (KPN). this simcard has bultin nfc for contactless payment.
but my phone seys: no simcard.

![screenshot_2016-01-25-20-21-22](https://cloud.githubusercontent.com/assets/16885675/12561619/65023184-c3a1-11e5-9caf-151fe1a526a3.png)

**Comment by grueda2** [comment]
I have a trouble like this, when I start the phone without the gapps I can use de mobile data and the calls, but when I install the gapps it show me an error "the process com.android.phone has stoped"  How can I fix it?

**Comment by DarthKeizer** [comment]
Clean install, so format everything should do the trick

**Comment by grueda2** [comment]
Thanks for reply.

I do a clean install from the March 14th update and it works perfectly.

2016-03-19 9:29 GMT-05:00 DarthKeizer notifications@github.com:

**Comment by DarthKeizer** [comment]
Close the issue if it is fixed :) my fellow dutchman

**Comment by grueda2** [comment]
In this moment I have another trouble, when I use the phone to see vídeos
on youtube or use the MHL cable this warm up until I can't use it.

You know anything about this?

Thanks.
