### ISSUE TITLE
Loss of audio for notification sounds

### ISSUE THREAD

**Issue by FernBch** [JDCTeam/issue_tracking_cm#86]
I've been experiencing it lost of audio for notification sound. I reboot seems to fix it temporarily. I do not know if it is affecting ringtone audio.

Logcat

https://www.dropbox.com/s/lxlpctg6ouxy6md/Log_2016-03-21_12-25-59.txt?dl=0

**Comment by B--B** [comment]
03-21 12:24:29.595   279 30946 E OMXNodeInstance: setConfig(3f:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)

03-21 12:24:29.595   279 30946 I ACodec  : codec does not support config priority (err -2147483648)

03-21 12:24:29.596   279 30946 I MediaCodec: MediaCodec will operate in async mode

03-21 12:24:29.603   279 30944 E AudioFlinger: not enough memory for AudioTrack size=536871016

03-21 12:24:29.603   279 30944 E AudioFlinger: createTrack_l() initCheck failed -12; no control block?

03-21 12:24:29.603   279 30944 E AudioTrack: AudioFlinger could not create track, status: -12

03-21 12:24:29.603   279 30944 E AudioSink: Unable to create audio track

It' s an AOSP bug still not fixed on MM, see here: https://code.google.com/p/android/issues/detail?id=189051

Aosp bug tracker is full of this kind of reports

**Comment by FernBch** [comment]
I experienced it on the optimized cm13 but if it's in AOSP and unresolved in marshmallow there's no point in having this one open if there's already multiple.
