### ISSUE TITLE
No sim card

### ISSUE THREAD

**Issue by myselfnotyou** [JDCTeam/issue_tracking_cm#87]
From time to time my phone reports no sim card. 
I was not able to identify what is triggering the problem.

![screenshot_20160322-121720](https://cloud.githubusercontent.com/assets/18004402/13948372/4fa1fb9a-f028-11e5-9d61-231424ad14a4.png)

Last time happened today.
I switched airplane mode on and back off and the sim was detected again.
After that in about 5 minutes the phone restarted it self and again the message with no sim card appeared.
Restarted again the phone and now is back OK
Please let me know if you have any idea how to slove it.

**Comment by DarthKeizer** [comment]
Bro, 
1. Format everything
2. Convert to F2FS
3. Clean install

Fixed it for me!

**Comment by myselfnotyou** [comment]
I am doing a clean install after converting to F2FS.
I like this ROM and I wanna use it.
I will give it one more try.

Thanks for the advice
