### ISSUE TITLE
No Audio for Outgoing Calls

### ISSUE THREAD

**Issue by Skitzmix2000** [JDCTeam/issue_tracking_cm#88]
Model: GT-i9507
Baseband i9507xxuhoj1
Rom Ver: 20160312
open gapps arm 6.0 nano 20160227
Clean install
rebooted
no system mod
original kernel
no xposed
no superSU

When ever i make an outgoing call i cant hear it ring or the other person answer the call but they can hear me. If i enable loudspeaker i can hear them and when i turn off loudspeaker  the phone earpiece is now working. Incoming calls work fine its just everytime i make an outgoing call i need to flip loudspeaker on then off to hear them.
[2016-03-27-18-51-40.txt](https://github.com/JDCTeam/issue_tracking_cm/files/191169/2016-03-27-18-51-40.txt)

**Comment by iGneousRock** [comment]
Same problem! When i make an outgoing call I cannot even hear the Ringing! This sucks especially when I have an important phone call

**Comment by tdakanalis** [comment]
Same problems here. I think these issues have been inherited from CM.
