### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Means1cK** [JDCTeam/issue_tracking_cm#93]
I am runninge the optimized cm13 2904 in my Galaxy s4 and Bluetooth is constantly crashing.
Die a clean install.

How can i help you?

**Comment by Means1cK** [comment]
GT i9505
I9505XXUHOJ2
Gapps from banks

**Comment by RichardoC** [comment]
Try clearing the data from "Bluetooth Share" app in settings, that fixed it for me

**Comment by Means1cK** [comment]
Thanks.. But it didn't work for me
